# ==========================================
# MEGA QUESTIONS DATABASE
# ==========================================

EMOJI_PUZZLES = [
    # Hollywood Movies
    {"e": "🦁👑", "ans": "The Lion King", "opts": ["The Lion King", "Madagascar", "Tarzan", "Jurassic Park"]},
    {"e": "🕷️🕸️🦸‍♂️", "ans": "Spiderman", "opts": ["Spiderman", "Batman", "Superman", "Ironman"]},
    {"e": "🚢🧊💔", "ans": "Titanic", "opts": ["Titanic", "Avatar", "Speed", "The Matrix"]},
    {"e": "🧙‍♂️👓⚡", "ans": "Harry Potter", "opts": ["Harry Potter", "Lord of the Rings", "Star Wars", "Percy Jackson"]},
    {"e": "🦇🃏😈", "ans": "Batman", "opts": ["Batman", "Joker", "Venom", "The Dark Knight"]},
    {"e": "👨‍🚀🪐⏳", "ans": "Interstellar", "opts": ["Interstellar", "Gravity", "Inception", "The Martian"]},
    {"e": "🤠🚀🦖", "ans": "Jurassic Park", "opts": ["Jurassic Park", "Toy Story", "The Good Dinosaur", "Ice Age"]},
    {"e": "💍🌋🧝‍♂️", "ans": "Lord of the Rings", "opts": ["Lord of the Rings", "The Hobbit", "Game of Thrones", "Willow"]},
    {"e": "🦈🌊😱", "ans": "Jaws", "opts": ["Jaws", "Deep Blue Sea", "Meg", "Piranha"]},
    {"e": "👻🔪📞", "ans": "Scream", "opts": ["Scream", "Halloween", "The Ring", "It"]},
    {"e": "🤖⏳🔥", "ans": "Terminator", "opts": ["Terminator", "Transformers", "RoboCop", "Blade Runner"]},
    {"e": "🚿🔪😨", "ans": "Psycho", "opts": ["Psycho", "The Shining", "Halloween", "Saw"]},
    {"e": "🌍🤝👽", "ans": "Arrival", "opts": ["Arrival", "Independence Day", "Signs", "E.T."]},
    {"e": "🚗💨😡", "ans": "Fast and Furious", "opts": ["Fast and Furious", "Mad Max", "Need for Speed", "Drive"]},
    {"e": "🏴‍☠️🦜💎", "ans": "Pirates of the Caribbean", "opts": ["Pirates of the Caribbean", "Treasure Island", "Hook", "Black Sails"]},
    {"e": "🐼🥋🥢", "ans": "Kung Fu Panda", "opts": ["Kung Fu Panda", "Mulan", "Crouching Tiger", "Hidden Dragon"]},
    {"e": "🐠🔎🌊", "ans": "Finding Nemo", "opts": ["Finding Nemo", "Finding Dory", "Shark Tale", "The Little Mermaid"]},
    {"e": "🐜👖🦸‍♂️", "ans": "Antman", "opts": ["Antman", "Hulk", "Spiderman", "Ironman"]},
    {"e": "🐒🌴🛰️", "ans": "Planet of the Apes", "opts": ["Planet of the Apes", "Jungle Book", "Tarzan", "King Kong"]},
    {"e": "❄️👑👗", "ans": "Frozen", "opts": ["Frozen", "Tangled", "Moana", "Brave"]},
    {"e": "👹🧄🧛‍♂️", "ans": "Twilight", "opts": ["Twilight", "Vampire Diaries", "Dracula", "Underworld"]},
    {"e": "🤠🌌🦖", "ans": "Toy Story", "opts": ["Toy Story", "Wall-E", "Up", "Coco"]},
    {"e": "🤖🗑️🌍", "ans": "Wall-E", "opts": ["Wall-E", "Interstellar", "The Martian", "Avatar"]},
    {"e": "🐀👨‍🍳🍲", "ans": "Ratatouille", "opts": ["Ratatouille", "Chef", "Julie & Julia", "Burnt"]},
    {"e": "👨‍👨‍👧🎈🏠", "ans": "Up", "opts": ["Up", "Inside Out", "Coco", "Finding Nemo"]},
    {"e": "🧠😡😢", "ans": "Inside Out", "opts": ["Inside Out", "The Emoji Movie", "Soul", "Coco"]},
    {"e": "💀🎸🎸", "ans": "School of Rock", "opts": ["School of Rock", "Rockstar", "Bohemian Rhapsody", "Rocketman"]},
    {"e": "🦇🦇🧛‍♂️", "ans": "Dracula", "opts": ["Dracula", "Twilight", "Blade", "Van Helsing"]},
    {"e": "🌌⚔️💚", "ans": "Guardians of the Galaxy", "opts": ["Guardians of the Galaxy", "Star Wars", "Star Trek", "Avatar"]},
    {"e": "⚡🔨🦱", "ans": "Thor", "opts": ["Thor", "Loki", "Aquaman", "Shazam"]},
    {"e": "🇺🇸🛡️💪", "ans": "Captain America", "opts": ["Captain America", "Ironman", "Hulk", "Thor"]},
    {"e": "🏹👧🔥", "ans": "The Hunger Games", "opts": ["The Hunger Games", "Divergent", "Maze Runner", "Twilight"]},
    {"e": "🚗🤖👽", "ans": "Transformers", "opts": ["Transformers", "Terminator", "Pacific Rim", "Real Steel"]},
    {"e": "🐧🏴‍☠️🕺", "ans": "Happy Feet", "opts": ["Happy Feet", "Madagascar", "Ice Age", "Penguins of Madagascar"]},
    {"e": "👹😳🤫", "ans": "Shrek", "opts": ["Shrek", "Monsters Inc", "Monsters University", "Hotel Transylvania"]},
    {"e": "👔👓💻", "ans": "The Matrix", "opts": ["The Matrix", "Inception", "Interstellar", "The Social Network"]},
    {"e": "🦁🐷🐒", "ans": "The Jungle Book", "opts": ["The Jungle Book", "Tarzan", "George of the Jungle", "Madagascar"]},
    {"e": "🚀🪨💥", "ans": "Armageddon", "opts": ["Armageddon", "Deep Impact", "Gravity", "The Martian"]},
    {"e": "🌋🚂🦖", "ans": "Journey to the Center of the Earth", "opts": ["Journey to the Center of the Earth", "Jurassic Park", "The Land Before Time", "King Kong"]},
    {"e": "🦒🦛🦁", "ans": "Madagascar", "opts": ["Madagascar", "The Lion King", "Jumanji", "Zootopia"]},
    {"e": "🐰🦊🕵️", "ans": "Zootopia", "opts": ["Zootopia", "Tangled", "Big Hero 6", "Bolt"]},
    {"e": "🦸‍♂️🤳📱", "ans": "Deadpool", "opts": ["Deadpool", "Wolverine", "X-Men", "Spawn"]},
    {"e": "🤡🎈🎈", "ans": "It", "opts": ["It", "The Shining", "Annabelle", "The Conjuring"]},
    {"e": "👁️🚪👻", "ans": "The Conjuring", "opts": ["The Conjuring", "Insidious", "Sinister", "The Exorcist"]},
    {"e": "🚪✨👧", "ans": "Coraline", "opts": ["Coraline", "ParaNorman", "Frankenweenie", "Monster House"]},
    {"e": "👻🍔📺", "ans": "Ghostbusters", "opts": ["Ghostbusters", "Men in Black", "Evolution", "Paul"]},
    {"e": "👽🚗🛸", "ans": "E.T.", "opts": ["E.T.", "Alien", "Signs", "Arrival"]},
    {"e": "🤠😨👽", "ans": "Cowboys & Aliens", "opts": ["Cowboys & Aliens", "Wild Wild West", "MIB", "Westworld"]},
    {"e": "🕺💥🚗", "ans": "Baby Driver", "opts": ["Baby Driver", "Drive", "The Transporter", "Taxi"]},
    {"e": "🐼🎋❤️", "ans": "Kung Fu Panda", "opts": ["Kung Fu Panda", "Mulan", "Crouching Tiger", "Hero"]},

    # Bollywood Movies
    {"e": "🇮🇳🏏🏆", "ans": "Lagaan", "opts": ["Lagaan", "Chak De India", "Iqbal", "MS Dhoni"]},
    {"e": "🐕🦮🚂", "ans": "Kuch Kuch Hota Hai", "opts": ["Kuch Kucha Hota Hai", "DDLJ", "Kabhi Khushi Kabhie Gham", "Student of the Year"]},
    {"e": "🚂🇨🇳❤️", "ans": "Dilwale Dulhania Le Jayenge", "opts": ["Dilwale Dulhania Le Jayenge", "Kuch Kuch Hota Hai", "Yeh Jawaani Hai Deewani", "Chennai Express"]},
    {"e": "🎤🎸🕺", "ans": "Rockstar", "opts": ["Rockstar", "Aashiqui 2", "Jaane Tu Ya Jaane Na", "Tamasha"]},
    {"e": "😎🏍️🚓", "ans": "Dhoom", "opts": ["Dhoom", "Race", "Bang Bang", "Don"]},
    {"e": "🤵🚉💃", "ans": "DDLJ", "opts": ["Dilwale Dulhania Le Jayenge", "Kuch Kuch Hota Hai", "Jab We Met", "Yeh Jawaani Hai Deewani"]},
    {"e": "🧔🧢🚗", "ans": "Dil Chahta Hai", "opts": ["Dil Chahta Hai", "Zindagi Na Milegi Dobara", "Dostana", "Rockford"]},
    {"e": "🚂🏃‍♂️❤️", "ans": "Jab We Met", "opts": ["Jab We Met", "Love Aaj Kal", "Tamasha", "Yeh Jawaani Hai Deewani"]},
    {"e": "🤴🇮🇳🚲", "ans": "M.S. Dhoni: The Untold Story", "opts": ["M.S. Dhoni", "Sachin: A Billion Dreams", "Chak De India", "Gold"]},
    {"e": "👮🚔🤵", "ans": "Singham", "opts": ["Singham", "Dabangg", "Rowdy Rathore", "Simmba"]},
    {"e": "👹🐍🙏", "ans": "Nagin", "opts": ["Nagin", "Jaani Dushman", "Mallika", "Hisss"]},
    {"e": "👯‍♀️💃🎉", "ans": "Cocktail", "opts": ["Cocktail", "Yeh Jawaani Hai Deewani", "Zindagi Na Milegi Dobara", "Dostana"]},
    {"e": "👻🤡🔪", "ans": "Stree", "opts": ["Stree", "Go Goa Gone", "Bhool Bhulaiyaa", "Roohi"]},
    {"e": "🚂👮‍♂️💥", "ans": "Sholay", "opts": ["Sholay", "Don", "Deewar", "Zanjeer"]},
    {"e": "🎒🎒✈️", "ans": "Zindagi Na Milegi Dobara", "opts": ["Zindagi Na Milegi Dobara", "Dil Chahta Hai", "Dostana", "Yeh Jawaani Hai Deewani"]},
    {"e": "🔫👑🩸", "ans": "Gangs of Wasseypur", "opts": ["Gangs of Wasseypur", "Satya", "Once Upon a Time in Mumbaai", "Shootout at Wadala"]},
    {"e": "🚾💧🚾", "ans": "Gully Boy", "opts": ["Gully Boy", "Rockstar", "Aashiqui 2", "Delhi Belly"]},
    {"e": "👰🚗💔", "ans": "Tanu Weds Manu", "opts": ["Tanu Weds Manu", "Tanu Weds Manu Returns", "Shubh Mangal Saavdhan", "Raanjhanaa"]},
    {"e": "🦇🧛‍♂️🇮🇳", "ans": "Bhool Bhulaiyaa", "opts": ["Bhool Bhulaiyaa", "Stree", "Go Goa Gone", "1920"]},
    {"e": "👨‍🦰🛺❤️", "ans": "Raanjhanaa", "opts": ["Raanjhanaa", "Tanu Weds Manu", "Aanand L Rai", "Shubh Mangal Saavdhan"]}
]

BRAIN_QUESTIONS = [
    # Math & Logic
    {"q": "Agar 5 machines 5 min me 5 shirt banati hain, toh 100 machines 100 shirt kitne min me banayengi?", "opts": ["100 min", "5 min", "20 min", "50 min"], "ans": "5 min"},
    {"q": "Doctor ne 3 dawai di, har 30 min baad leni hai. Sab khatam hone me kitna time lagega?", "opts": ["90 min", "30 min", "60 min", "1.5 hours"], "ans": "60 min"},
    {"q": "Ek gaadi me 3 pehriyan (wheels) aur 4 tyre hain. Ye kya hai?", "opts": ["Ek gaadi", "Tyre", "Cycle", "Tractor"], "ans": "Tyre"},
    {"q": "Aisi kya cheez hai jo gir to jati hai, par tutti nahi?", "opts": ["Aasoo", "Raat", "Saanp", "Patta"], "ans": "Raat"},
    {"q": "Agar tum 1 ko 1 se jodo to 1 aata hai. Ye kya hai?", "opts": ["Maths", "Knot (Ganth)", "Pencil", "Line"], "ans": "Knot (Ganth)"},
    {"q": "Ek farmer ko 17 bhed hain. Sab mar gaye except 9. Kitne bache?", "opts": ["8", "9", "17", "0"], "ans": "9"},
    {"q": "Bina haath pair ke kaun building bana sakta hai?", "opts": ["Insaan", "Machine", "Makdi (Spider)", "Makkhi"], "ans": "Makdi (Spider)"},
    {"q": "Aisi kya cheez hai jo utna zyada kato, utni badi hoti hai?", "opts": ["Darwaza", "Soorakh (Hole)", "Pencil", "Kapda"], "ans": "Soorakh (Hole)"},
    {"q": "Agar 2 company 2 polio banaati hai, toh 100 company kitna polio banayengi?", "opts": ["100", "2", "50", "200"], "ans": "2"},
    {"q": "Main aisi hoon jo hamesha aage rehti hoon, par tum mujhe kabhi nahi dekh sakte. Main kya hoon?", "opts": ["Kal", "Aasmaan", "Hawa", "Dhoop"], "ans": "Kal"},
    {"q": "Kaun si sabzi ko katne se uski aawaz aati hai?", "opts": ["Pyaaz", "Tamatar", "Gajar", "Bandh gobhi"], "ans": "Pyaaz"},
    {"q": "Aisi kya cheez hai jise andar se khaali karne par wo bhari hua dikhta hai?", "opts": ["Khopcha", "Botel", "Botal", "Pair"], "ans": "Botel"},
    {"q": "Agar tumhare paas 3 apple hain aur tumne 2 le liye, toh tumhare paas kitne hain?", "opts": ["2", "3", "1", "5"], "ans": "2"},
    {"q": "Aisi kya cheez hai jo barish me nahi bheegti?", "opts": ["Paani", "Kapde", "Aaina", "Chhatri"], "ans": "Paani"},
    {"q": "Main aisa number batao jo 1 se zyada hai par kisi bhi number se devide nahi hota?", "opts": ["Prime Number", "Even Number", "Odd Number", "Complex Number"], "ans": "Prime Number"},

    # Science & Nature
    {"q": "Pani ka chemical formula kya hai?", "opts": ["CO2", "H2O", "O2", "NaCl"], "ans": "H2O"},
    {"q": "Duniya ka sabse bada island kaunsa hai?", "opts": ["Australia", "Greenland", "Sri Lanka", "India"], "ans": "Greenland"},
    {"q": "Bharat ka national animal kaunsa hai?", "opts": ["Lion", "Tiger", "Elephant", "Leopard"], "ans": "Tiger"},
    {"q": "Kaun sa janwar aaine me apna hi chehra dekh kar heran hota hai?", "opts": ["Kutta", "Billi", "Bandar", "Sher"], "ans": "Bandar"},
    {"q": "Duniya ka sabse uncha pahaad kaunsa hai?", "opts": ["K2", "Kanchenjunga", "Mount Everest", "Nanda Devi"], "ans": "Mount Everest"},
    {"q": "Sabse zyada kis gas se plants khana banate hain?", "opts": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], "ans": "Carbon Dioxide"},
    {"q": "Insaan ke shareer me sabse zyada kya hai?", "opts": ["Water (Pani)", "Blood (Khoon)", "Bones (Haddi)", "Fat (Charbi)"], "ans": "Water (Pani)"},
    {"q": "Kaun sa planet 'Red Planet' kehlata hai?", "opts": ["Mars", "Venus", "Jupiter", "Saturn"], "ans": "Mars"},
    {"q": "Duniya ka sabse bada ocean kaunsa hai?", "opts": ["Pacific", "Atlantic", "Indian", "Arctic"], "ans": "Pacific"},
    {"q": "Kaun si cheez heart (dil) ko pump karti hai?", "opts": ["Blood", "Oxygen", "Brain", "Muscles"], "ans": "Blood"},

    # History & General Knowledge
    {"q": "Mahatma Gandhi ko sabse zyada kise pyar tha?", "opts": ["Truth", "Money", "Power", "Fame"], "ans": "Truth"},
    {"q": "Sabse zyada kis desh ki cricket team ko world cup mila hai?", "opts": ["India", "West Indies", "Australia", "England"], "ans": "Australia"},
    {"q": "Bharat ki rajdhani kya hai?", "opts": ["Mumbai", "Kolkata", "New Delhi", "Chennai"], "ans": "New Delhi"},
    {"q": "Taj Mahal kis shahar me hai?", "opts": ["Delhi", "Agra", "Jaipur", "Lucknow"], "ans": "Agra"},
    {"q": "Bharat ka pehle Prime Minister kaun the?", "opts": ["Sardar Patel", "Jawaharlal Nehru", "Rajendra Prasad", "Lal Bahadur Shastri"], "ans": "Jawaharlal Nehru"},
    {"q": "Bharat ka constitution kab bana tha?", "opts": ["1947", "1949", "1950", "1952"], "ans": "1950"},
    {"q": "National Bird of India kaunsa hai?", "opts": ["Kaawa", "Mor (Peacock)", "Tota", "Kabootar"], "ans": "Mor (Peacock)"},
    {"q": "Which is the smallest country in the world?", "opts": ["Maldives", "Vatican City", "Monaco", "Sri Lanka"], "ans": "Vatican City"},
    {"q": "Bharat me 1 rupee ki sikka (coin) kis dhaatu se banti hai?", "opts": ["Sona", "Chandi", "Copper", "Steel"], "ans": "Steel"},

    # Fun & Riddles
    {"q": "Kaun sa din week ka sabse acha hota hai?", "opts": ["Monday", "Sunday", "Friday", "Saturday"], "ans": "Sunday"},
    {"q": "Jo khud bhooka rehta hai par dusron ko khilata hai, wo kaun?", "opts": ["Cook", "Farmer", "Doctor", "Driver"], "ans": "Cook"},
    {"q": "Aisi kya cheez hai jo utna zyada chhilke (peel) utni chhoti hoti hai?", "opts": ["Seb", "Kela", "Pyaaz", "Anaar"], "ans": "Pyaaz"},
    {"q": "Aisi kya cheez hai jise agar tum doba do to wo sukh (dry) ho jati hai?", "opts": ["Kapda", "Bンバナ Sponge", "Tauliya", "Pani"], "ans": "Tauliya"},
    {"q": "Aisa kaun hai jo bol nahi sakta par sabki sunta hai?", "opts": ["Bhains", "Kaanha", "Andha", "Behra"], "ans": "Bhains"},
    {"q": "Main aisi hoon jitna tum mujhe pehchano, utni main door ho jaati hoon. Main kya hoon?", "opts": ["Puzzle", "Dream", "Secret (Raaz)", "Night"], "ans": "Secret (Raaz)"},
    {"q": "Aisi kya cheez hai joagar tumne usko naam lekar bulaya to wo tut jati hai?", "opts": ["Aaina", "Kanch", "Shaanti (Silence)", "Toota hua dil"], "ans": "Shaanti (Silence)"},
    {"q": "Ek thaili (bag) me kya hai jo isko halka banata hai?", "opts": ["Hawa", "Kapde", "Pustak", "Pani"], "ans": "Hawa"},
    {"q": "Kaun sa fal mitai me aata hai aur sabzi me bhi?", "opts": ["Seb", "Kela", "Gajar", "Tamatar"], "ans": "Gajar"},
    {"q": "Kaun sa kaam hai jo tum akela nahi kar sakte?", "opts": ["Shaadi", "Khana", "Sona", "Hasna"], "ans": "Shaadi"}
]
