# ==========================================
# MEGA QUESTIONS DATABASE (No Duplicates)
# ==========================================

EMOJI_PUZZLES = [
    # Hollywood
    {"e": "🦁👑", "ans": "The Lion King", "opts": ["The Lion King", "Madagascar", "Tarzan", "Jurassic Park"]},
    {"e": "🕷️🧑", "ans": "Spider-Man", "opts": ["Spider-Man", "Batman", "Superman", "Iron Man"]},
    {"e": "🚢🧊💔", "ans": "Titanic", "opts": ["Titanic", "The Notebook", "Avatar", "Jaws"]},
    {"e": "🦖🏝️", "ans": "Jurassic Park", "opts": ["Jurassic Park", "King Kong", "Godzilla", "Jumanji"]},
    {"e": "🤖❤️", "ans": "WALL-E", "opts": ["WALL-E", "Transformers", "RoboCop", "Chappie"]},
    {"e": "👻🚫", "ans": "Ghostbusters", "opts": ["Ghostbusters", "Casper", "Beetlejuice", "The Conjuring"]},
    {"e": "🧙‍♂️⚡", "ans": "Harry Potter", "opts": ["Harry Potter", "The Lord of the Rings", "Fantastic Beasts", "Percy Jackson"]},
    {"e": "🦇🦸", "ans": "The Dark Knight", "opts": ["The Dark Knight", "Batman Begins", "Joker", "Man of Steel"]},
    {"e": "🚗💨🏁", "ans": "Fast & Furious", "opts": ["Fast & Furious", "Need for Speed", "Cars", "Ford v Ferrari"]},
    {"e": "👽📞🏠", "ans": "E.T.", "opts": ["E.T.", "Alien", "Arrival", "Men in Black"]},
    {"e": "🧊👸❄️", "ans": "Frozen", "opts": ["Frozen", "Moana", "Tangled", "Brave"]},
    {"e": "🐼🥋", "ans": "Kung Fu Panda", "opts": ["Kung Fu Panda", "Madagascar", "Zootopia", "Ratatouille"]},
    {"e": "🧠🌌", "ans": "Inception", "opts": ["Inception", "Interstellar", "Tenet", "The Matrix"]},
    {"e": "🌌🚀👨‍🚀", "ans": "Interstellar", "opts": ["Interstellar", "Gravity", "The Martian", "Inception"]},
    {"e": "🧟‍♂️🚂", "ans": "Train to Busan", "opts": ["Train to Busan", "World War Z", "Zombieland", "28 Days Later"]},
    {"e": "🐠🔍", "ans": "Finding Nemo", "opts": ["Finding Nemo", "The Little Mermaid", "Shark Tale", "Moana"]},
    {"e": "👸🐸", "ans": "The Princess and the Frog", "opts": ["The Princess and the Frog", "Cinderella", "Shrek", "Beauty and the Beast"]},
    {"e": "🚢🏴‍☠️", "ans": "Pirates of the Caribbean", "opts": ["Pirates of the Caribbean", "Peter Pan", "Treasure Planet", "Hook"]},
    {"e": "🧞‍♂️🪔", "ans": "Aladdin", "opts": ["Aladdin", "Hercules", "Mulan", "Moana"]},
    {"e": "🦍🏙️", "ans": "King Kong", "opts": ["King Kong", "Godzilla", "Rampage", "Planet of the Apes"]},
    {"e": "🌊🐠❤️", "ans": "The Little Mermaid", "opts": ["The Little Mermaid", "Finding Nemo", "Moana", "Luca"]},
    {"e": "🦸‍♂️🛡️", "ans": "Captain America", "opts": ["Captain America", "Iron Man", "Thor", "Hulk"]},
    {"e": "🔨⚡", "ans": "Thor", "opts": ["Thor", "Hulk", "Aquaman", "Shazam!"]},
    {"e": "🤡🃏", "ans": "Joker", "opts": ["Joker", "The Dark Knight", "It", "Deadpool"]},
    {"e": "🧙‍♂️💍", "ans": "The Lord of the Rings", "opts": ["The Lord of the Rings", "Harry Potter", "The Hobbit", "Willow"]},
    {"e": "🚀🌕", "ans": "The Martian", "opts": ["The Martian", "Gravity", "Interstellar", "Apollo 13"]},
    {"e": "🐯👨", "ans": "Life of Pi", "opts": ["Life of Pi", "The Jungle Book", "The Revenant", "Cast Away"]},
    {"e": "👨‍🦱💰🏠", "ans": "Money Heist", "opts": ["Money Heist", "Now You See Me", "Ocean's Eleven", "The Italian Job"]},
    {"e": "🤖⏳🔥", "ans": "Terminator", "opts": ["Terminator", "Transformers", "RoboCop", "Blade Runner"]},
    {"e": "🚿🔪😨", "ans": "Psycho", "opts": ["Psycho", "The Shining", "Halloween", "Saw"]},
    {"e": "🌍🤝👽", "ans": "Arrival", "opts": ["Arrival", "Independence Day", "Signs", "E.T."]},
    {"e": "🐜👖🦸‍♂️", "ans": "Antman", "opts": ["Antman", "Hulk", "Spiderman", "Ironman"]},
    {"e": "🐒🌴🛰️", "ans": "Planet of the Apes", "opts": ["Planet of the Apes", "Jungle Book", "Tarzan", "King Kong"]},
    {"e": "👹😳🤫", "ans": "Shrek", "opts": ["Shrek", "Monsters Inc", "Monsters University", "Hotel Transylvania"]},
    {"e": "👔👓💻", "ans": "The Matrix", "opts": ["The Matrix", "Inception", "Interstellar", "The Social Network"]},
    {"e": "🦒🦛🦁", "ans": "Madagascar", "opts": ["Madagascar", "The Lion King", "Jumanji", "Zootopia"]},
    {"e": "🐰🦊🕵️", "ans": "Zootopia", "opts": ["Zootopia", "Tangled", "Big Hero 6", "Bolt"]},
    {"e": "🦸‍♂️🤳📱", "ans": "Deadpool", "opts": ["Deadpool", "Wolverine", "X-Men", "Spawn"]},
    {"e": "🤡🎈🎈", "ans": "It", "opts": ["It", "The Shining", "Annabelle", "The Conjuring"]},
    {"e": "👁️🚪👻", "ans": "The Conjuring", "opts": ["The Conjuring", "Insidious", "Sinister", "The Exorcist"]},
    {"e": "🚪✨👧", "ans": "Coraline", "opts": ["Coraline", "ParaNorman", "Frankenweenie", "Monster House"]},
    {"e": "🤠😨👽", "ans": "Cowboys & Aliens", "opts": ["Cowboys & Aliens", "Wild Wild West", "MIB", "Westworld"]},
    {"e": "🕺💥🚗", "ans": "Baby Driver", "opts": ["Baby Driver", "Drive", "The Transporter", "Taxi"]},
    {"e": "👹🧄🧛‍♂️", "ans": "Twilight", "opts": ["Twilight", "Vampire Diaries", "Dracula", "Underworld"]},
    {"e": "🤠🌌🦖", "ans": "Toy Story", "opts": ["Toy Story", "Wall-E", "Up", "Coco"]},
    {"e": "🐀👨‍🍳🍲", "ans": "Ratatouille", "opts": ["Ratatouille", "Chef", "Julie & Julia", "Burnt"]},
    {"e": "👨‍👨‍👧🎈🏠", "ans": "Up", "opts": ["Up", "Inside Out", "Coco", "Finding Nemo"]},
    {"e": "🧠😡😢", "ans": "Inside Out", "opts": ["Inside Out", "The Emoji Movie", "Soul", "Coco"]},
    {"e": "💀🎸🎸", "ans": "School of Rock", "opts": ["School of Rock", "Rockstar", "Bohemian Rhapsody", "Rocketman"]},
    {"e": "🦇🦇🧛‍♂️", "ans": "Dracula", "opts": ["Dracula", "Twilight", "Blade", "Van Helsing"]},
    {"e": "🌌⚔️💚", "ans": "Guardians of the Galaxy", "opts": ["Guardians of the Galaxy", "Star Wars", "Star Trek", "Avatar"]},
    {"e": "🏹👧🔥", "ans": "The Hunger Games", "opts": ["The Hunger Games", "Divergent", "Maze Runner", "Twilight"]},
    {"e": "🚗🤖👽", "ans": "Transformers", "opts": ["Transformers", "Terminator", "Pacific Rim", "Real Steel"]},
    {"e": "🐧🏴‍☠️🕺", "ans": "Happy Feet", "opts": ["Happy Feet", "Madagascar", "Ice Age", "Penguins of Madagascar"]},
    {"e": "🦁🐷🐒", "ans": "The Jungle Book", "opts": ["The Jungle Book", "Tarzan", "George of the Jungle", "Madagascar"]},
    {"e": "🚀🪨💥", "ans": "Armageddon", "opts": ["Armageddon", "Deep Impact", "Gravity", "The Martian"]},
    {"e": "🌋🚂🦖", "ans": "Journey to the Center of the Earth", "opts": ["Journey to the Center of the Earth", "Jurassic Park", "The Land Before Time", "King Kong"]},
    {"e": "🦈🌊😱", "ans": "Jaws", "opts": ["Jaws", "Deep Blue Sea", "Meg", "Piranha"]},
    {"e": "👻🔪📞", "ans": "Scream", "opts": ["Scream", "Halloween", "The Ring", "It"]},
    
    # Bollywood
    {"e": "3️⃣🤪", "ans": "3 Idiots", "opts": ["3 Idiots", "Chhichhore", "PK", "Munna Bhai M.B.B.S."]},
    {"e": "🤖❤️👦", "ans": "Krrish", "opts": ["Krrish", "Ra.One", "Robot", "Dhoom 3"]},
    {"e": "👨‍🎓👻", "ans": "Stree", "opts": ["Stree", "Bhool Bhulaiyaa", "Bhootnath", "Munjya"]},
    {"e": "💔🎸", "ans": "Aashiqui 2", "opts": ["Aashiqui 2", "Rockstar", "Ek Villain", "Sanam Teri Kasam"]},
    {"e": "👽🤔", "ans": "PK", "opts": ["PK", "Koi... Mil Gaya", "Oh My God", "3 Idiots"]},
    {"e": "💃🕺🚂", "ans": "Chennai Express", "opts": ["Chennai Express", "Dilwale", "Happy New Year", "Raees"]},
    {"e": "🏏👨‍👦", "ans": "Jersey", "opts": ["Jersey", "83", "MS Dhoni: The Untold Story", "Lagaan"]},
    {"e": "👰🚂❤️", "ans": "Dilwale Dulhania Le Jayenge", "opts": ["Dilwale Dulhania Le Jayenge", "Veer-Zaara", "Kuch Kuch Hota Hai", "Kal Ho Naa Ho"]},
    {"e": "👻🏠🔔", "ans": "Bhool Bhulaiyaa", "opts": ["Bhool Bhulaiyaa", "Stree", "Bhootnath", "Munjya"]},
    {"e": "💪🇮🇳", "ans": "Dangal", "opts": ["Dangal", "Sultan", "Bhaag Milkha Bhaag", "Mary Kom"]},
    {"e": "👨‍👩‍👧‍👦❤️", "ans": "Kabhi Khushi Kabhie Gham", "opts": ["Kabhi Khushi Kabhie Gham", "Kal Ho Naa Ho", "Baghban", "Hum Saath Saath Hain"]},
    {"e": "🏍️💨😎", "ans": "Dhoom", "opts": ["Dhoom", "Race", "Don", "War"]},
    {"e": "🧔🪓🔥", "ans": "Pushpa", "opts": ["Pushpa", "KGF", "Salaar", "RRR"]},
    {"e": "🇮🇳🏏🏆", "ans": "83", "opts": ["83", "Lagaan", "Jersey", "MS Dhoni: The Untold Story"]},
    {"e": "🚂👬❤️", "ans": "Zindagi Na Milegi Dobara", "opts": ["Zindagi Na Milegi Dobara", "Dil Chahta Hai", "Yeh Jawaani Hai Deewani", "Chhichhore"]},
    {"e": "🎤💃👑", "ans": "Rockstar", "opts": ["Rockstar", "Aashiqui 2", "Tamasha", "Ae Dil Hai Mushkil"]},
    {"e": "🕵️‍♂️💣🔥", "ans": "War", "opts": ["War", "Pathaan", "Tiger Zinda Hai", "Dhoom 2"]},
    {"e": "🐘❤️👨", "ans": "Haathi Mere Saathi", "opts": ["Haathi Mere Saathi", "Dangal", "Bajrangi Bhaijaan", "Baghban"]},
    {"e": "👨‍🚀🌕🇮🇳", "ans": "Mission Mangal", "opts": ["Mission Mangal", "Chandrayaan", "Rocketry", "Swades"]},
    {"e": "🦁👨‍👩‍👧", "ans": "Bajrangi Bhaijaan", "opts": ["Bajrangi Bhaijaan", "Sultan", "Kick", "Dabangg"]},
    {"e": "🔥🔥🚂", "ans": "Sholay", "opts": ["Sholay", "Don", "Deewar", "Gangs of Wasseypur"]},
    {"e": "💀🌸💃", "ans": "Gangubai Kathiawadi", "opts": ["Gangubai Kathiawadi", "Padmaavat", "Devdas", "Bajirao Mastani"]},
    {"e": "🇮🇳🏏🏆", "ans": "Lagaan", "opts": ["Lagaan", "Chak De India", "Iqbal", "MS Dhoni"]},
    {"e": "🐕🦮🚂", "ans": "Kuch Kuch Hota Hai", "opts": ["Kuch Kuch Hota Hai", "DDLJ", "Kabhi Khushi Kabhie Gham", "Student of the Year"]},
    {"e": "🧔🧢🚗", "ans": "Dil Chahta Hai", "opts": ["Dil Chahta Hai", "Zindagi Na Milegi Dobara", "Dostana", "Rockford"]},
    {"e": "🚂🏃‍♂️❤️", "ans": "Jab We Met", "opts": ["Jab We Met", "Love Aaj Kal", "Tamasha", "Yeh Jawaani Hai Deewani"]},
    {"e": "🤴🇮🇳🚲", "ans": "M.S. Dhoni: The Untold Story", "opts": ["M.S. Dhoni", "Sachin: A Billion Dreams", "Chak De India", "Gold"]},
    {"e": "👮🚔🤵", "ans": "Singham", "opts": ["Singham", "Dabangg", "Rowdy Rathore", "Simmba"]},
    {"e": "👹🐍🙏", "ans": "Nagin", "opts": ["Nagin", "Jaani Dushman", "Mallika", "Hisss"]},
    {"e": "👯‍♀️💃🎉", "ans": "Cocktail", "opts": ["Cocktail", "Yeh Jawaani Hai Deewani", "Zindagi Na Milegi Dobara", "Dostana"]},
    {"e": "🔫👑🩸", "ans": "Gangs of Wasseypur", "opts": ["Gangs of Wasseypur", "Satya", "Once Upon a Time in Mumbaai", "Shootout at Wadala"]},
    {"e": "🚾💧🚾", "ans": "Gully Boy", "opts": ["Gully Boy", "Rockstar", "Aashiqui 2", "Delhi Belly"]},
    {"e": "👰🚗💔", "ans": "Tanu Weds Manu", "opts": ["Tanu Weds Manu", "Tanu Weds Manu Returns", "Shubh Mangal Saavdhan", "Raanjhanaa"]},
    {"e": "👨‍🦰🛺❤️", "ans": "Raanjhanaa", "opts": ["Raanjhanaa", "Tanu Weds Manu", "Aanand L Rai", "Shubh Mangal Saavdhan"]},
    {"e": "🧔⚔️🏔️", "ans": "KGF", "opts": ["KGF", "Pushpa", "Salaar", "RRR"]},
    {"e": "🐒💪🔥", "ans": "Hanuman", "opts": ["Hanuman", "Adipurush", "Kantara", "Kalki 2898 AD"]},
    {"e": "🚂🔥🇮🇳", "ans": "RRR", "opts": ["RRR", "KGF", "Pushpa", "Baahubali"]},
    {"e": "👑⚔️🏰", "ans": "Baahubali", "opts": ["Baahubali", "Padmaavat", "Jodhaa Akbar", "KGF"]},
    {"e": "🌲👻🧑", "ans": "Munjya", "opts": ["Munjya", "Stree", "Bhool Bhulaiyaa", "Bhediya"]},
    {"e": "🐺🌕👨", "ans": "Bhediya", "opts": ["Bhediya", "Munjya", "Stree", "Animal"]},
    {"e": "🐅🔫🇮🇳", "ans": "Tiger Zinda Hai", "opts": ["Tiger Zinda Hai", "War", "Pathaan", "Dhoom 3"]},
    {"e": "🕵️‍♂️🇮🇳🔥", "ans": "Pathaan", "opts": ["Pathaan", "Jawan", "War", "Raees"]},
    {"e": "👨‍🦲🔫🚂", "ans": "Jawan", "opts": ["Jawan", "Pathaan", "Don", "Raees"]},
    {"e": "🐘👦❤️", "ans": "Bajrangi Bhaijaan", "opts": ["Bajrangi Bhaijaan", "Dangal", "Sultan", "Kick"]},
    {"e": "👨‍🎓🎓❤️", "ans": "Chhichhore", "opts": ["Chhichhore", "3 Idiots", "Student of the Year", "PK"]},
    {"e": "🧳✈️👬", "ans": "Dil Chahta Hai", "opts": ["Dil Chahta Hai", "Zindagi Na Milegi Dobara", "Yeh Jawaani Hai Deewani", "Chhichhore"]},
    {"e": "👰💔🌧️", "ans": "Devdas", "opts": ["Devdas", "Bajirao Mastani", "Padmaavat", "Gangubai Kathiawadi"]},
    {"e": "👑💃🛡️", "ans": "Padmaavat", "opts": ["Padmaavat", "Bajirao Mastani", "Jodhaa Akbar", "Devdas"]},
    {"e": "⚔️❤️👑", "ans": "Bajirao Mastani", "opts": ["Bajirao Mastani", "Padmaavat", "Jodhaa Akbar", "Baahubali"]},
    {"e": "🏃‍♂️💨🥛", "ans": "Bhaag Milkha Bhaag", "opts": ["Bhaag Milkha Bhaag", "Dangal", "Sultan", "83"]},
    {"e": "🥊👩🇮🇳", "ans": "Mary Kom", "opts": ["Mary Kom", "Dangal", "Sultan", "Bhaag Milkha Bhaag"]},
    {"e": "🏏🌾🇮🇳", "ans": "Lagaan", "opts": ["Lagaan", "83", "Jersey", "Dangal"]},
    {"e": "👨‍⚕️😂🏥", "ans": "Munna Bhai M.B.B.S.", "opts": ["Munna Bhai M.B.B.S.", "3 Idiots", "PK", "Chhichhore"]},
    {"e": "👽👧❤️", "ans": "Koi... Mil Gaya", "opts": ["Koi... Mil Gaya", "PK", "Krrish", "Ra.One"]},
    {"e": "🤖🔴⚡", "ans": "Ra.One", "opts": ["Ra.One", "Krrish", "Robot", "Enthiran"]},
    {"e": "🐼🍜🥋", "ans": "Kung Fu Panda 2", "opts": ["Kung Fu Panda 2", "Kung Fu Panda", "Turning Red", "Zootopia"]},
    {"e": "🧸🤠🚀", "ans": "Toy Story", "opts": ["Toy Story", "Cars", "WALL-E", "Up"]},
    {"e": "🎈🏠👴", "ans": "Up", "opts": ["Up", "Coco", "Inside Out", "Soul"]},
    {"e": "🧠😊😢", "ans": "Inside Out", "opts": ["Inside Out", "Soul", "Coco", "Turning Red"]},
    {"e": "💀🎸🌸", "ans": "Coco", "opts": ["Coco", "Encanto", "Soul", "Moana"]},
    {"e": "🦸‍♂️🕶️🔴", "ans": "Deadpool", "opts": ["Deadpool", "Spider-Man", "Venom", "Iron Man"]},
    {"e": "🖤🕷️👅", "ans": "Venom", "opts": ["Venom", "Spider-Man", "Deadpool", "The Batman"]},
    {"e": "🧙‍♂️🌀✨", "ans": "Doctor Strange", "opts": ["Doctor Strange", "Harry Potter", "Thor", "The Matrix"]},
    {"e": "🟢💪💥", "ans": "The Hulk", "opts": ["The Hulk", "Shazam!", "Thor", "Superman"]},
    {"e": "🤖🚗⚔️", "ans": "Transformers", "opts": ["Transformers", "Real Steel", "Pacific Rim", "RoboCop"]},
    {"e": "🌊🦈😱", "ans": "Jaws", "opts": ["Jaws", "The Meg", "Titanic", "Finding Nemo"]},
    {"e": "🦍⚔️🦖", "ans": "Godzilla vs. Kong", "opts": ["Godzilla vs. Kong", "King Kong", "Jurassic Park", "Rampage"]},
    {"e": "🚗⚡🏁", "ans": "Cars", "opts": ["Cars", "Fast & Furious", "Toy Story", "Speed Racer"]},
    {"e": "👹🚪😱", "ans": "Monsters, Inc.", "opts": ["Monsters, Inc.", "Shrek", "Hotel Transylvania", "Monsters University"]},
    {"e": "🧅👹👸", "ans": "Shrek", "opts": ["Shrek", "Tangled", "Frozen", "Beauty and the Beast"]},
    {"e": "🐭👨‍🍳🍲", "ans": "Ratatouille", "opts": ["Ratatouille", "Chef", "The Menu", "Kung Fu Panda"]},
    {"e": "🏝️🏐👨", "ans": "Cast Away", "opts": ["Cast Away", "Life of Pi", "The Revenant", "The Martian"]},
    {"e": "🌪️🐕🏠", "ans": "The Wizard of Oz", "opts": ["The Wizard of Oz", "Alice in Wonderland", "Peter Pan", "Narnia"]},
    {"e": "👠🏰🎃", "ans": "Cinderella", "opts": ["Cinderella", "Snow White", "Frozen", "Beauty and the Beast"]},
    {"e": "🧜‍♀️🌊🐚", "ans": "The Little Mermaid", "opts": ["The Little Mermaid", "Moana", "Luca", "Finding Nemo"]},
    {"e": "🦁🐗🐒", "ans": "Madagascar", "opts": ["Madagascar", "The Lion King", "Zootopia", "Ice Age"]},
    {"e": "🦣❄️🐿️", "ans": "Ice Age", "opts": ["Ice Age", "Frozen", "Madagascar", "Happy Feet"]},
    {"e": "🐰🦊🏙️", "ans": "Zootopia", "opts": ["Zootopia", "Sing", "Madagascar", "Kung Fu Panda"]},
    {"e": "🎤🐨🐷", "ans": "Sing", "opts": ["Sing", "Zootopia", "Happy Feet", "Madagascar"]},
    {"e": "🧙‍♀️🦁🚪", "ans": "The Chronicles of Narnia", "opts": ["The Chronicles of Narnia", "Harry Potter", "The Lord of the Rings", "The Golden Compass"]},
    {"e": "🧊🚢🌊", "ans": "Poseidon", "opts": ["Poseidon", "Titanic", "The Perfect Storm", "Jaws"]},
    {"e": "💊🕶️💻", "ans": "The Matrix", "opts": ["The Matrix", "Inception", "Tenet", "Tron"]},
    {"e": "🕰️🔫🤵", "ans": "Tenet", "opts": ["Tenet", "Inception", "Interstellar", "The Matrix"]},
    {"e": "🌙🐺❤️", "ans": "Twilight", "opts": ["Twilight", "The Vampire Diaries", "Underworld", "Beautiful Creatures"]}
]

BRAIN_QUESTIONS = [
    # Math & Logic
    {"q": "Agar 5 machines 5 min me 5 shirt banati hain, toh 100 machines 100 shirt kitne min me banayengi?", "opts": ["100 min", "5 min", "20 min", "50 min"], "ans": "5 min"},
    {"q": "Doctor ne 3 dawai di, har 30 min baad leni hai. Sab khatam hone me kitna time lagega?", "opts": ["90 min", "30 min", "60 min", "1.5 hours"], "ans": "60 min"},
    {"q": "Ek gaadi me 3 pehriyan (wheels) aur 4 tyre hain. Ye kya hai?", "opts": ["Ek gaadi", "Tyre", "Cycle", "Tractor"], "ans": "Tyre"},
    {"q": "Aisi kya cheez hai jo gir to jati hai, par tutti nahi?", "opts": ["Aasoo", "Raat", "Saanp", "Patta"], "ans": "Raat"},
    {"q": "Agar tum 1 ko 1 se jodo to 1 aata hai. Ye kya hai?", "opts": ["Maths", "Knot (Ganth)", "Pencil", "Line"], "ans": "Knot (Ganth)"},
    {"q": "Ek farmer ko 17 bhed hain. Sab mar gaye except 9. Kitne bache?", "opts": ["8", "9", "17", "0"], "ans": "9"},
    {"q": "Bina haath pair ke kaun building bana sakta hai?", "opts": ["Insaan", "Machine", "Makdi (Spider)", "Makkhi"], "ans": "Makdi (Spider)"},
    {"q": "Aisi kya cheez hai jo utna zyada kato, utni badi hoti hai?", "opts": ["Darwaza", "Soorakh (Hole)", "Pencil", "Kapda"], "ans": "Soorakh (Hole)"},
    {"q": "Agar 2 company 2 polio banaati hai, toh 100 company kitna polio banayengi?", "opts": ["100", "2", "50", "200"], "ans": "2"},
    {"q": "Main aisi hoon jo hamesha aage rehti hoon, par tum mujhe kabhi nahi dekh sakte. Main kya hoon?", "opts": ["Kal", "Aasmaan", "Hawa", "Dhoop"], "ans": "Kal"},
    {"q": "Kaun si sabzi ko katne se uski aawaz aati hai?", "opts": ["Pyaaz", "Tamatar", "Gajar", "Bandh gobhi"], "ans": "Pyaaz"},
    {"q": "Aisi kya cheez hai jise andar se khaali karne par wo bhari hua dikhta hai?", "opts": ["Khopcha", "Botel", "Botal", "Pair"], "ans": "Botel"},
    {"q": "Agar tumhare paas 3 apple hain aur tumne 2 le liye, toh tumhare paas kitne hain?", "opts": ["2", "3", "1", "5"], "ans": "2"},
    {"q": "Aisi kya cheez hai jo barish me nahi bheegti?", "opts": ["Paani", "Kapde", "Aaina", "Chhatri"], "ans": "Paani"},
    {"q": "Main aisa number batao jo 1 se zyada hai par kisi bhi number se devide nahi hota?", "opts": ["Prime Number", "Even Number", "Odd Number", "Complex Number"], "ans": "Prime Number"},

    # Science & Nature
    {"q": "Pani ka chemical formula kya hai?", "opts": ["CO2", "H2O", "O2", "NaCl"], "ans": "H2O"},
    {"q": "Duniya ka sabse bada island kaunsa hai?", "opts": ["Australia", "Greenland", "Sri Lanka", "India"], "ans": "Greenland"},
    {"q": "Bharat ka national animal kaunsa hai?", "opts": ["Lion", "Tiger", "Elephant", "Leopard"], "ans": "Tiger"},
    {"q": "Kaun sa janwar aaine me apna hi chehra dekh kar heran hota hai?", "opts": ["Kutta", "Billi", "Bandar", "Sher"], "ans": "Bandar"},
    {"q": "Duniya ka sabse uncha pahaad kaunsa hai?", "opts": ["K2", "Kanchenjunga", "Mount Everest", "Nanda Devi"], "ans": "Mount Everest"},
    {"q": "Sabse zyada kis gas se plants khana banate hain?", "opts": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], "ans": "Carbon Dioxide"},
    {"q": "Insaan ke shareer me sabse zyada kya hai?", "opts": ["Water (Pani)", "Blood (Khoon)", "Bones (Haddi)", "Fat (Charbi)"], "ans": "Water (Pani)"},
    {"q": "Kaun sa planet 'Red Planet' kehlata hai?", "opts": ["Mars", "Venus", "Jupiter", "Saturn"], "ans": "Mars"},
    {"q": "Duniya ka sabse bada ocean kaunsa hai?", "opts": ["Pacific", "Atlantic", "Indian", "Arctic"], "ans": "Pacific"},
    {"q": "Kaun si cheez heart (dil) ko pump karti hai?", "opts": ["Blood", "Oxygen", "Brain", "Muscles"], "ans": "Blood"},

    # History & General Knowledge
    {"q": "Mahatma Gandhi ko sabse zyada kise pyar tha?", "opts": ["Truth", "Money", "Power", "Fame"], "ans": "Truth"},
    {"q": "Sabse zyada kis desh ki cricket team ko world cup mila hai?", "opts": ["India", "West Indies", "Australia", "England"], "ans": "Australia"},
    {"q": "Bharat ki rajdhani kya hai?", "opts": ["Mumbai", "Kolkata", "New Delhi", "Chennai"], "ans": "New Delhi"},
    {"q": "Taj Mahal kis shahar me hai?", "opts": ["Delhi", "Agra", "Jaipur", "Lucknow"], "ans": "Agra"},
    {"q": "Bharat ka pehle Prime Minister kaun the?", "opts": ["Sardar Patel", "Jawaharlal Nehru", "Rajendra Prasad", "Lal Bahadur Shastri"], "ans": "Jawaharlal Nehru"},
    {"q": "Bharat ka constitution kab bana tha?", "opts": ["1947", "1949", "1950", "1952"], "ans": "1950"},
    {"q": "National Bird of India kaunsa hai?", "opts": ["Kaawa", "Mor (Peacock)", "Tota", "Kabootar"], "ans": "Mor (Peacock)"},
    {"q": "Which is the smallest country in the world?", "opts": ["Maldives", "Vatican City", "Monaco", "Sri Lanka"], "ans": "Vatican City"},
    {"q": "Bharat me 1 rupee ki sikka (coin) kis dhaatu se banti hai?", "opts": ["Sona", "Chandi", "Copper", "Steel"], "ans": "Steel"},

    # Fun & Riddles
    {"q": "Kaun sa din week ka sabse acha hota hai?", "opts": ["Monday", "Sunday", "Friday", "Saturday"], "ans": "Sunday"},
    {"q": "Jo khud bhooka rehta hai par dusron ko khilata hai, wo kaun?", "opts": ["Cook", "Farmer", "Doctor", "Driver"], "ans": "Cook"},
    {"q": "Aisi kya cheez hai jo utna zyada chhilke (peel) utni chhoti hoti hai?", "opts": ["Seb", "Kela", "Pyaaz", "Anaar"], "ans": "Pyaaz"},
    {"q": "Aisi kya cheez hai jise agar tum doba do to wo sukh (dry) ho jati hai?", "opts": ["Kapda", "Sponge", "Tauliya", "Pani"], "ans": "Tauliya"},
    {"q": "Aisa kaun hai jo bol nahi sakta par sabki sunta hai?", "opts": ["Bhains", "Kaanha", "Andha", "Behra"], "ans": "Bhains"},
    {"q": "Main aisi hoon jitna tum mujhe pehchano, utni main door ho jaati hoon. Main kya hoon?", "opts": ["Puzzle", "Dream", "Secret (Raaz)", "Night"], "ans": "Secret (Raaz)"},
    {"q": "Aisi kya cheez hai joagar tumne usko naam lekar bulaya to wo tut jati hai?", "opts": ["Aaina", "Kanch", "Shaanti (Silence)", "Toota hua dil"], "ans": "Shaanti (Silence)"},
    {"q": "Ek thaili (bag) me kya hai jo isko halka banata hai?", "opts": ["Hawa", "Kapde", "Pustak", "Pani"], "ans": "Hawa"},
    {"q": "Kaun sa fal mitai me aata hai aur sabzi me bhi?", "opts": ["Seb", "Kela", "Gajar", "Tamatar"], "ans": "Gajar"},
    {"q": "Kaun sa kaam hai jo tum akela nahi kar sakte?", "opts": ["Shaadi", "Khana", "Sona", "Hasna"], "ans": "Shaadi"}
]

# ==========================================
# WORD GUESS (CROSSWORD STYLE)
# ==========================================
WORD_PUZZLES = [
    {"q": "Clue: Khan banane ki jagah (8 letters)", "ans": "Rasoighar", "opts": ["Rasoighar", "Bedroom", "Drawing Room", "Bathroom"]},
    {"q": "Clue: Rozana liya jane wala aarthik sahayata (8 letters)", "ans": "Tankhwa", "opts": ["Tankhwa", "Bakshish", "Chanda", "Byaj"]},
    {"q": "Clue: Aasmaan me chamakne wali cheez (6 letters)", "ans": "Tara", "opts": ["Tara", "Badal", "Chand", "Sooraj"]},
    {"q": "Clue: Pedon se milne wali hari patte (5 letters)", "ans": "Patti", "opts": ["Patti", "Jad", "Daali", "Phal"]},
    {"q": "Clue: Pani me tairne wala janwar (4 letters)", "ans": "Machh", "opts": ["Machh", "Kachhua", "Magarmach", "Beng"]},
    {"q": "Clue: Vidyalaya jane wale bachhe (7 letters)", "ans": "Chhatra", "opts": ["Chhatra", "Adhyapak", "Pradhanacharya", "Praj"]},
    {"q": "Clue: Vehicle chalane wala vyakti (6 letters)", "ans": "Chalak", "opts": ["Chalak", "Yatri", "Conductor", "Police"]},
    {"q": "Clue: Dhoop se milne wali garmi (5 letters)", "ans": "Tapish", "opts": ["Tapish", "Aag", "Pasina", "Hawa"]},
    {"q": "Clue: Khelne ke liye prayukt kitaab (5 letters)", "ans": "Patri", "opts": ["Patri", "Kalam", "Dasta", "Baksa"]},
    {"q": "Clue: Bhojan karne ka sthan (6 letters)", "ans": "Bhojnal", "opts": ["Bhojnal", "Rasoighar", "Kaksh", "Prishth"]},
    {"q": "Clue: Vastuon ko rakha jata hai isme (5 letters)", "ans": "Almari", "opts": ["Almari", "Mez", "Khat", "Kursi"]},
    {"q": "Clue: Time dekhne ka yantra (5 letters)", "ans": "Ghadi", "opts": ["Ghadi", "Calculator", "Calendar", "Phone"]},
    {"q": "Clue: Barish me upyog ki jati hai (7 letters)", "ans": "Chhatri", "opts": ["Chhatri", "Duniya", "Pankha", "Balti"]},
    {"q": "Clue: Likhne ka kaam aata hai (5 letters)", "ans": "Kalam", "opts": ["Kalam", "Rubber", "Scale", "Pencil"]},
    {"q": "Clue: Pahaad ki choti (5 letters)", "ans": "Shikhar", "opts": ["Shikhar", "Ghati", "Jungle", "Nadi"]},
    {"q": "Clue: Andhera hatane ke liye (6 letters)", "ans": "Batti", "opts": ["Batti", "Pankha", "Khidki", "Darwaza"]},
    {"q": "Clue: Mithaas ke liye upyog (5 letters)", "ans": "Cheeni", "opts": ["Cheeni", "Namak", "Mirch", "Haldi"]},
    {"q": "Clue: Ped se milkar aata hai (4 letters)", "ans": "Phal", "opts": ["Phal", "Sabzi", "Khet", "Beej"]},
    {"q": "Clue: Raat ko sone ka sthan (4 letters)", "ans": "Khat", "opts": ["Khat", "Mez", "Sofa", "Jamghat"]},
    {"q": "Clue: Dawai dene wala vyakti (5 letters)", "ans": "Vaidya", "opts": ["Vaidya", "Rogi", "Sipahi", "Nars"]}
]
