# ==========================================
# MEGA QUESTIONS DATABASE (No Duplicates)
# ==========================================

EMOJI_PUZZLES = [
    # Hollywood
    {"e": "🦁👑", "ans": "The Lion King", "opts": ["The Lion King", "Madagascar", "Tarzan", "Jurassic Park"]},
    {"e": "🕷️🧑", "ans": "Spider-Man", "opts": ["Spider-Man", "Batman", "Superman", "Iron Man"]},
    {"e": "🚢🧊💔", "ans": "Titanic", "opts": ["Titanic", "The Notebook", "Avatar", "Jaws"]},
    {"e": "🦖🏝️", "ans": "Jurassic Park", "opts": ["Jurassic Park", "King Kong", "Godzilla", "Jumanji"]},
    {"e": "🤖❤️", "ans": "WALL-E", "opts": ["WALL-E", "Transformers", "RoboCop", "Chappie"]},
    {"e": "👻🚫", "ans": "Ghostbusters", "opts": ["Ghostbusters", "Casper", "Beetlejuice", "The Conjuring"]},
    {"e": "🧙‍♂️⚡", "ans": "Harry Potter", "opts": ["Harry Potter", "The Lord of the Rings", "Fantastic Beasts", "Percy Jackson"]},
    {"e": "🦇🦸", "ans": "The Dark Knight", "opts": ["The Dark Knight", "Batman Begins", "Joker", "Man of Steel"]},
    {"e": "🚗💨🏁", "ans": "Fast & Furious", "opts": ["Fast & Furious", "Need for Speed", "Cars", "Ford v Ferrari"]},
    {"e": "👽📞🏠", "ans": "E.T.", "opts": ["E.T.", "Alien", "Arrival", "Men in Black"]},
    {"e": "🧊👸❄️", "ans": "Frozen", "opts": ["Frozen", "Moana", "Tangled", "Brave"]},
    {"e": "🐼🥋", "ans": "Kung Fu Panda", "opts": ["Kung Fu Panda", "Madagascar", "Zootopia", "Ratatouille"]},
    {"e": "🧠🌌", "ans": "Inception", "opts": ["Inception", "Interstellar", "Tenet", "The Matrix"]},
    {"e": "🌌🚀👨‍🚀", "ans": "Interstellar", "opts": ["Interstellar", "Gravity", "The Martian", "Inception"]},
    {"e": "🧟‍♂️🚂", "ans": "Train to Busan", "opts": ["Train to Busan", "World War Z", "Zombieland", "28 Days Later"]},
    {"e": "🐠🔍", "ans": "Finding Nemo", "opts": ["Finding Nemo", "The Little Mermaid", "Shark Tale", "Moana"]},
    {"e": "👸🐸", "ans": "The Princess and the Frog", "opts": ["The Princess and the Frog", "Cinderella", "Shrek", "Beauty and the Beast"]},
    {"e": "🚢🏴‍☠️", "ans": "Pirates of the Caribbean", "opts": ["Pirates of the Caribbean", "Peter Pan", "Treasure Planet", "Hook"]},
    {"e": "🧞‍♂️🪔", "ans": "Aladdin", "opts": ["Aladdin", "Hercules", "Mulan", "Moana"]},
    {"e": "🦍🏙️", "ans": "King Kong", "opts": ["King Kong", "Godzilla", "Rampage", "Planet of the Apes"]},
    {"e": "🌊🐠❤️", "ans": "The Little Mermaid", "opts": ["The Little Mermaid", "Finding Nemo", "Moana", "Luca"]},
    {"e": "🦸‍♂️🛡️", "ans": "Captain America", "opts": ["Captain America", "Iron Man", "Thor", "Hulk"]},
    {"e": "🔨⚡", "ans": "Thor", "opts": ["Thor", "Hulk", "Aquaman", "Shazam!"]},
    {"e": "🤡🃏", "ans": "Joker", "opts": ["Joker", "The Dark Knight", "It", "Deadpool"]},
    {"e": "🧙‍♂️💍", "ans": "The Lord of the Rings", "opts": ["The Lord of the Rings", "Harry Potter", "The Hobbit", "Willow"]},
    {"e": "🚀🌕", "ans": "The Martian", "opts": ["The Martian", "Gravity", "Interstellar", "Apollo 13"]},
    {"e": "🐯👨", "ans": "Life of Pi", "opts": ["Life of Pi", "The Jungle Book", "The Revenant", "Cast Away"]},
    {"e": "👨‍🦱💰🏠", "ans": "Money Heist", "opts": ["Money Heist", "Now You See Me", "Ocean's Eleven", "The Italian Job"]},
    {"e": "🤖⏳🔥", "ans": "Terminator", "opts": ["Terminator", "Transformers", "RoboCop", "Blade Runner"]},
    {"e": "🚿🔪😨", "ans": "Psycho", "opts": ["Psycho", "The Shining", "Halloween", "Saw"]},
    {"e": "🌍🤝👽", "ans": "Arrival", "opts": ["Arrival", "Independence Day", "Signs", "E.T."]},
    {"e": "🐜👖🦸‍♂️", "ans": "Antman", "opts": ["Antman", "Hulk", "Spiderman", "Ironman"]},
    {"e": "🐒🌴🛰️", "ans": "Planet of the Apes", "opts": ["Planet of the Apes", "Jungle Book", "Tarzan", "King Kong"]},
    {"e": "👹😳🤫", "ans": "Shrek", "opts": ["Shrek", "Monsters Inc", "Monsters University", "Hotel Transylvania"]},
    {"e": "👔👓💻", "ans": "The Matrix", "opts": ["The Matrix", "Inception", "Interstellar", "The Social Network"]},
    {"e": "🦒🦛🦁", "ans": "Madagascar", "opts": ["Madagascar", "The Lion King", "Jumanji", "Zootopia"]},
    {"e": "🐰🦊🕵️", "ans": "Zootopia", "opts": ["Zootopia", "Tangled", "Big Hero 6", "Bolt"]},
    {"e": "🦸‍♂️🤳📱", "ans": "Deadpool", "opts": ["Deadpool", "Wolverine", "X-Men", "Spawn"]},
    {"e": "🤡🎈🎈", "ans": "It", "opts": ["It", "The Shining", "Annabelle", "The Conjuring"]},
    {"e": "👁️🚪👻", "ans": "The Conjuring", "opts": ["The Conjuring", "Insidious", "Sinister", "The Exorcist"]},
    {"e": "🚪✨👧", "ans": "Coraline", "opts": ["Coraline", "ParaNorman", "Frankenweenie", "Monster House"]},
    {"e": "🤠😨👽", "ans": "Cowboys & Aliens", "opts": ["Cowboys & Aliens", "Wild Wild West", "MIB", "Westworld"]},
    {"e": "🕺💥🚗", "ans": "Baby Driver", "opts": ["Baby Driver", "Drive", "The Transporter", "Taxi"]},
    {"e": "👹🧄🧛‍♂️", "ans": "Twilight", "opts": ["Twilight", "Vampire Diaries", "Dracula", "Underworld"]},
    {"e": "🤠🌌🦖", "ans": "Toy Story", "opts": ["Toy Story", "Wall-E", "Up", "Coco"]},
    {"e": "🐀👨‍🍳🍲", "ans": "Ratatouille", "opts": ["Ratatouille", "Chef", "Julie & Julia", "Burnt"]},
    {"e": "👨‍👨‍👧🎈🏠", "ans": "Up", "opts": ["Up", "Inside Out", "Coco", "Finding Nemo"]},
    {"e": "🧠😡😢", "ans": "Inside Out", "opts": ["Inside Out", "The Emoji Movie", "Soul", "Coco"]},
    {"e": "💀🎸🎸", "ans": "School of Rock", "opts": ["School of Rock", "Rockstar", "Bohemian Rhapsody", "Rocketman"]},
    {"e": "🦇🦇🧛‍♂️", "ans": "Dracula", "opts": ["Dracula", "Twilight", "Blade", "Van Helsing"]},
    {"e": "🌌⚔️💚", "ans": "Guardians of the Galaxy", "opts": ["Guardians of the Galaxy", "Star Wars", "Star Trek", "Avatar"]},
    {"e": "🏹👧🔥", "ans": "The Hunger Games", "opts": ["The Hunger Games", "Divergent", "Maze Runner", "Twilight"]},
    {"e": "🚗🤖👽", "ans": "Transformers", "opts": ["Transformers", "Terminator", "Pacific Rim", "Real Steel"]},
    {"e": "🐧🏴‍☠️🕺", "ans": "Happy Feet", "opts": ["Happy Feet", "Madagascar", "Ice Age", "Penguins of Madagascar"]},
    {"e": "🦁🐷🐒", "ans": "The Jungle Book", "opts": ["The Jungle Book", "Tarzan", "George of the Jungle", "Madagascar"]},
    {"e": "🚀🪨💥", "ans": "Armageddon", "opts": ["Armageddon", "Deep Impact", "Gravity", "The Martian"]},
    {"e": "🌋🚂🦖", "ans": "Journey to the Center of the Earth", "opts": ["Journey to the Center of the Earth", "Jurassic Park", "The Land Before Time", "King Kong"]},
    {"e": "🦈🌊😱", "ans": "Jaws", "opts": ["Jaws", "Deep Blue Sea", "Meg", "Piranha"]},
    {"e": "👻🔪📞", "ans": "Scream", "opts": ["Scream", "Halloween", "The Ring", "It"]},
    
    # Bollywood
    {"e": "3️⃣🤪", "ans": "3 Idiots", "opts": ["3 Idiots", "Chhichhore", "PK", "Munna Bhai M.B.B.S."]},
    {"e": "🤖❤️👦", "ans": "Krrish", "opts": ["Krrish", "Ra.One", "Robot", "Dhoom 3"]},
    {"e": "👨‍🎓👻", "ans": "Stree", "opts": ["Stree", "Bhool Bhulaiyaa", "Bhootnath", "Munjya"]},
    {"e": "💔🎸", "ans": "Aashiqui 2", "opts": ["Aashiqui 2", "Rockstar", "Ek Villain", "Sanam Teri Kasam"]},
    {"e": "👽🤔", "ans": "PK", "opts": ["PK", "Koi... Mil Gaya", "Oh My God", "3 Idiots"]},
    {"e": "💃🕺🚂", "ans": "Chennai Express", "opts": ["Chennai Express", "Dilwale", "Happy New Year", "Raees"]},
    {"e": "🏏👨‍👦", "ans": "Jersey", "opts": ["Jersey", "83", "MS Dhoni: The Untold Story", "Lagaan"]},
    {"e": "👰🚂❤️", "ans": "Dilwale Dulhania Le Jayenge", "opts": ["Dilwale Dulhania Le Jayenge", "Veer-Zaara", "Kuch Kuch Hota Hai", "Kal Ho Naa Ho"]},
    {"e": "👻🏠🔔", "ans": "Bhool Bhulaiyaa", "opts": ["Bhool Bhulaiyaa", "Stree", "Bhootnath", "Munjya"]},
    {"e": "💪🇮🇳", "ans": "Dangal", "opts": ["Dangal", "Sultan", "Bhaag Milkha Bhaag", "Mary Kom"]},
    {"e": "👨‍👩‍👧‍👦❤️", "ans": "Kabhi Khushi Kabhie Gham", "opts": ["Kabhi Khushi Kabhie Gham", "Kal Ho Naa Ho", "Baghban", "Hum Saath Saath Hain"]},
    {"e": "🏍️💨😎", "ans": "Dhoom", "opts": ["Dhoom", "Race", "Don", "War"]},
    {"e": "🧔🪓🔥", "ans": "Pushpa", "opts": ["Pushpa", "KGF", "Salaar", "RRR"]},
    {"e": "🇮🇳🏏🏆", "ans": "83", "opts": ["83", "Lagaan", "Jersey", "MS Dhoni: The Untold Story"]},
    {"e": "🚂👬❤️", "ans": "Zindagi Na Milegi Dobara", "opts": ["Zindagi Na Milegi Dobara", "Dil Chahta Hai", "Yeh Jawaani Hai Deewani", "Chhichhore"]},
    {"e": "🎤💃👑", "ans": "Rockstar", "opts": ["Rockstar", "Aashiqui 2", "Tamasha", "Ae Dil Hai Mushkil"]},
    {"e": "🕵️‍♂️💣🔥", "ans": "War", "opts": ["War", "Pathaan", "Tiger Zinda Hai", "Dhoom 2"]},
    {"e": "🐘❤️👨", "ans": "Haathi Mere Saathi", "opts": ["Haathi Mere Saathi", "Dangal", "Bajrangi Bhaijaan", "Baghban"]},
    {"e": "👨‍🚀🌕🇮🇳", "ans": "Mission Mangal", "opts": ["Mission Mangal", "Chandrayaan", "Rocketry", "Swades"]},
    {"e": "🦁👨‍👩‍👧", "ans": "Bajrangi Bhaijaan", "opts": ["Bajrangi Bhaijaan", "Sultan", "Kick", "Dabangg"]},
    {"e": "🔥🔥🚂", "ans": "Sholay", "opts": ["Sholay", "Don", "Deewar", "Gangs of Wasseypur"]},
    {"e": "💀🌸💃", "ans": "Gangubai Kathiawadi", "opts": ["Gangubai Kathiawadi", "Padmaavat", "Devdas", "Bajirao Mastani"]},
    {"e": "🇮🇳🏏🏆", "ans": "Lagaan", "opts": ["Lagaan", "Chak De India", "Iqbal", "MS Dhoni"]},
    {"e": "🐕🦮🚂", "ans": "Kuch Kuch Hota Hai", "opts": ["Kuch Kuch Hota Hai", "DDLJ", "Kabhi Khushi Kabhie Gham", "Student of the Year"]},
    {"e": "🧔🧢🚗", "ans": "Dil Chahta Hai", "opts": ["Dil Chahta Hai", "Zindagi Na Milegi Dobara", "Dostana", "Rockford"]},
    {"e": "🚂🏃‍♂️❤️", "ans": "Jab We Met", "opts": ["Jab We Met", "Love Aaj Kal", "Tamasha", "Yeh Jawaani Hai Deewani"]},
    {"e": "🤴🇮🇳🚲", "ans": "M.S. Dhoni: The Untold Story", "opts": ["M.S. Dhoni", "Sachin: A Billion Dreams", "Chak De India", "Gold"]},
    {"e": "👮🚔🤵", "ans": "Singham", "opts": ["Singham", "Dabangg", "Rowdy Rathore", "Simmba"]},
    {"e": "👹🐍🙏", "ans": "Nagin", "opts": ["Nagin", "Jaani Dushman", "Mallika", "Hisss"]},
    {"e": "👯‍♀️💃🎉", "ans": "Cocktail", "opts": ["Cocktail", "Yeh Jawaani Hai Deewani", "Zindagi Na Milegi Dobara", "Dostana"]},
    {"e": "🔫👑🩸", "ans": "Gangs of Wasseypur", "opts": ["Gangs of Wasseypur", "Satya", "Once Upon a Time in Mumbaai", "Shootout at Wadala"]},
    {"e": "🚾💧🚾", "ans": "Gully Boy", "opts": ["Gully Boy", "Rockstar", "Aashiqui 2", "Delhi Belly"]},
    {"e": "👰🚗💔", "ans": "Tanu Weds Manu", "opts": ["Tanu Weds Manu", "Tanu Weds Manu Returns", "Shubh Mangal Saavdhan", "Raanjhanaa"]},
    {"e": "👨‍🦰🛺❤️", "ans": "Raanjhanaa", "opts": ["Raanjhanaa", "Tanu Weds Manu", "Aanand L Rai", "Shubh Mangal Saavdhan"]},
    {"e": "🧔⚔️🏔️", "ans": "KGF", "opts": ["KGF", "Pushpa", "Salaar", "RRR"]},
    {"e": "🐒💪🔥", "ans": "Hanuman", "opts": ["Hanuman", "Adipurush", "Kantara", "Kalki 2898 AD"]},
    {"e": "🚂🔥🇮🇳", "ans": "RRR", "opts": ["RRR", "KGF", "Pushpa", "Baahubali"]},
    {"e": "👑⚔️🏰", "ans": "Baahubali", "opts": ["Baahubali", "Padmaavat", "Jodhaa Akbar", "KGF"]},
    {"e": "🌲👻🧑", "ans": "Munjya", "opts": ["Munjya", "Stree", "Bhool Bhulaiyaa", "Bhediya"]},
    {"e": "🐺🌕👨", "ans": "Bhediya", "opts": ["Bhediya", "Munjya", "Stree", "Animal"]},
    {"e": "🐅🔫🇮🇳", "ans": "Tiger Zinda Hai", "opts": ["Tiger Zinda Hai", "War", "Pathaan", "Dhoom 3"]},
    {"e": "🕵️‍♂️🇮🇳🔥", "ans": "Pathaan", "opts": ["Pathaan", "Jawan", "War", "Raees"]},
    {"e": "👨‍🦲🔫🚂", "ans": "Jawan", "opts": ["Jawan", "Pathaan", "Don", "Raees"]},
    {"e": "🐘👦❤️", "ans": "Bajrangi Bhaijaan", "opts": ["Bajrangi Bhaijaan", "Dangal", "Sultan", "Kick"]},
    {"e": "👨‍🎓🎓❤️", "ans": "Chhichhore", "opts": ["Chhichhore", "3 Idiots", "Student of the Year", "PK"]},
    {"e": "🧳✈️👬", "ans": "Dil Chahta Hai", "opts": ["Dil Chahta Hai", "Zindagi Na Milegi Dobara", "Yeh Jawaani Hai Deewani", "Chhichhore"]},
    {"e": "👰💔🌧️", "ans": "Devdas", "opts": ["Devdas", "Bajirao Mastani", "Padmaavat", "Gangubai Kathiawadi"]},
    {"e": "👑💃🛡️", "ans": "Padmaavat", "opts": ["Padmaavat", "Bajirao Mastani", "Jodhaa Akbar", "Devdas"]},
    {"e": "⚔️❤️👑", "ans": "Bajirao Mastani", "opts": ["Bajirao Mastani", "Padmaavat", "Jodhaa Akbar", "Baahubali"]},
    {"e": "🏃‍♂️💨🥛", "ans": "Bhaag Milkha Bhaag", "opts": ["Bhaag Milkha Bhaag", "Dangal", "Sultan", "83"]},
    {"e": "🥊👩🇮🇳", "ans": "Mary Kom", "opts": ["Mary Kom", "Dangal", "Sultan", "Bhaag Milkha Bhaag"]},
    {"e": "🏏🌾🇮🇳", "ans": "Lagaan", "opts": ["Lagaan", "83", "Jersey", "Dangal"]},
    {"e": "👨‍⚕️😂🏥", "ans": "Munna Bhai M.B.B.S.", "opts": ["Munna Bhai M.B.B.S.", "3 Idiots", "PK", "Chhichhore"]},
    {"e": "👽👧❤️", "ans": "Koi... Mil Gaya", "opts": ["Koi... Mil Gaya", "PK", "Krrish", "Ra.One"]},
    {"e": "🤖🔴⚡", "ans": "Ra.One", "opts": ["Ra.One", "Krrish", "Robot", "Enthiran"]},
    {"e": "🐼🍜🥋", "ans": "Kung Fu Panda 2", "opts": ["Kung Fu Panda 2", "Kung Fu Panda", "Turning Red", "Zootopia"]},
    {"e": "🧸🤠🚀", "ans": "Toy Story", "opts": ["Toy Story", "Cars", "WALL-E", "Up"]},
    {"e": "🎈🏠👴", "ans": "Up", "opts": ["Up", "Coco", "Inside Out", "Soul"]},
    {"e": "🧠😊😢", "ans": "Inside Out", "opts": ["Inside Out", "Soul", "Coco", "Turning Red"]},
    {"e": "💀🎸🌸", "ans": "Coco", "opts": ["Coco", "Encanto", "Soul", "Moana"]},
    {"e": "🦸‍♂️🕶️🔴", "ans": "Deadpool", "opts": ["Deadpool", "Spider-Man", "Venom", "Iron Man"]},
    {"e": "🖤🕷️👅", "ans": "Venom", "opts": ["Venom", "Spider-Man", "Deadpool", "The Batman"]},
    {"e": "🧙‍♂️🌀✨", "ans": "Doctor Strange", "opts": ["Doctor Strange", "Harry Potter", "Thor", "The Matrix"]},
    {"e": "🟢💪💥", "ans": "The Hulk", "opts": ["The Hulk", "Shazam!", "Thor", "Superman"]},
    {"e": "🤖🚗⚔️", "ans": "Transformers", "opts": ["Transformers", "Real Steel", "Pacific Rim", "RoboCop"]},
    {"e": "🌊🦈😱", "ans": "Jaws", "opts": ["Jaws", "The Meg", "Titanic", "Finding Nemo"]},
    {"e": "🦍⚔️🦖", "ans": "Godzilla vs. Kong", "opts": ["Godzilla vs. Kong", "King Kong", "Jurassic Park", "Rampage"]},
    {"e": "🚗⚡🏁", "ans": "Cars", "opts": ["Cars", "Fast & Furious", "Toy Story", "Speed Racer"]},
    {"e": "👹🚪😱", "ans": "Monsters, Inc.", "opts": ["Monsters, Inc.", "Shrek", "Hotel Transylvania", "Monsters University"]},
    {"e": "🧅👹👸", "ans": "Shrek", "opts": ["Shrek", "Tangled", "Frozen", "Beauty and the Beast"]},
    {"e": "🐭👨‍🍳🍲", "ans": "Ratatouille", "opts": ["Ratatouille", "Chef", "The Menu", "Kung Fu Panda"]},
    {"e": "🏝️🏐👨", "ans": "Cast Away", "opts": ["Cast Away", "Life of Pi", "The Revenant", "The Martian"]},
    {"e": "🌪️🐕🏠", "ans": "The Wizard of Oz", "opts": ["The Wizard of Oz", "Alice in Wonderland", "Peter Pan", "Narnia"]},
    {"e": "👠🏰🎃", "ans": "Cinderella", "opts": ["Cinderella", "Snow White", "Frozen", "Beauty and the Beast"]},
    {"e": "🧜‍♀️🌊🐚", "ans": "The Little Mermaid", "opts": ["The Little Mermaid", "Moana", "Luca", "Finding Nemo"]},
    {"e": "🦁🐗🐒", "ans": "Madagascar", "opts": ["Madagascar", "The Lion King", "Zootopia", "Ice Age"]},
    {"e": "🦣❄️🐿️", "ans": "Ice Age", "opts": ["Ice Age", "Frozen", "Madagascar", "Happy Feet"]},
    {"e": "🐰🦊🏙️", "ans": "Zootopia", "opts": ["Zootopia", "Sing", "Madagascar", "Kung Fu Panda"]},
    {"e": "🎤🐨🐷", "ans": "Sing", "opts": ["Sing", "Zootopia", "Happy Feet", "Madagascar"]},
    {"e": "🧙‍♀️🦁🚪", "ans": "The Chronicles of Narnia", "opts": ["The Chronicles of Narnia", "Harry Potter", "The Lord of the Rings", "The Golden Compass"]},
    {"e": "🧊🚢🌊", "ans": "Poseidon", "opts": ["Poseidon", "Titanic", "The Perfect Storm", "Jaws"]},
    {"e": "💊🕶️💻", "ans": "The Matrix", "opts": ["The Matrix", "Inception", "Tenet", "Tron"]},
    {"e": "🕰️🔫🤵", "ans": "Tenet", "opts": ["Tenet", "Inception", "Interstellar", "The Matrix"]},
    {"e": "🌙🐺❤️", "ans": "Twilight", "opts": ["Twilight", "The Vampire Diaries", "Underworld", "Beautiful Creatures"]}
]

BRAIN_QUESTIONS = [
    # Math & Logic
    {"q": "Agar 5 machines 5 min me 5 shirt banati hain, toh 100 machines 100 shirt kitne min me banayengi?", "opts": ["100 min", "5 min", "20 min", "50 min"], "ans": "5 min"},
    {"q": "Doctor ne 3 dawai di, har 30 min baad leni hai. Sab khatam hone me kitna time lagega?", "opts": ["90 min", "30 min", "60 min", "1.5 hours"], "ans": "60 min"},
    {"q": "Ek gaadi me 3 pehriyan (wheels) aur 4 tyre hain. Ye kya hai?", "opts": ["Ek gaadi", "Tyre", "Cycle", "Tractor"], "ans": "Tyre"},
    {"q": "Aisi kya cheez hai jo gir to jati hai, par tutti nahi?", "opts": ["Aasoo", "Raat", "Saanp", "Patta"], "ans": "Raat"},
    {"q": "Agar tum 1 ko 1 se jodo to 1 aata hai. Ye kya hai?", "opts": ["Maths", "Knot (Ganth)", "Pencil", "Line"], "ans": "Knot (Ganth)"},
    {"q": "Ek farmer ko 17 bhed hain. Sab mar gaye except 9. Kitne bache?", "opts": ["8", "9", "17", "0"], "ans": "9"},
    {"q": "Bina haath pair ke kaun building bana sakta hai?", "opts": ["Insaan", "Machine", "Makdi (Spider)", "Makkhi"], "ans": "Makdi (Spider)"},
    {"q": "Aisi kya cheez hai jo utna zyada kato, utni badi hoti hai?", "opts": ["Darwaza", "Soorakh (Hole)", "Pencil", "Kapda"], "ans": "Soorakh (Hole)"},
    {"q": "Agar 2 company 2 polio banaati hai, toh 100 company kitna polio banayengi?", "opts": ["100", "2", "50", "200"], "ans": "2"},
    {"q": "Main aisi hoon jo hamesha aage rehti hoon, par tum mujhe kabhi nahi dekh sakte. Main kya hoon?", "opts": ["Kal", "Aasmaan", "Hawa", "Dhoop"], "ans": "Kal"},
    {"q": "Kaun si sabzi ko katne se uski aawaz aati hai?", "opts": ["Pyaaz", "Tamatar", "Gajar", "Bandh gobhi"], "ans": "Pyaaz"},
    {"q": "Aisi kya cheez hai jise andar se khaali karne par wo bhari hua dikhta hai?", "opts": ["Khopcha", "Botel", "Botal", "Pair"], "ans": "Botel"},
    {"q": "Agar tumhare paas 3 apple hain aur tumne 2 le liye, toh tumhare paas kitne hain?", "opts": ["2", "3", "1", "5"], "ans": "2"},
    {"q": "Aisi kya cheez hai jo barish me nahi bheegti?", "opts": ["Paani", "Kapde", "Aaina", "Chhatri"], "ans": "Paani"},
    {"q": "Main aisa number batao jo 1 se zyada hai par kisi bhi number se devide nahi hota?", "opts": ["Prime Number", "Even Number", "Odd Number", "Complex Number"], "ans": "Prime Number"},

    # Science & Nature
    {"q": "Pani ka chemical formula kya hai?", "opts": ["CO2", "H2O", "O2", "NaCl"], "ans": "H2O"},
    {"q": "Duniya ka sabse bada island kaunsa hai?", "opts": ["Australia", "Greenland", "Sri Lanka", "India"], "ans": "Greenland"},
    {"q": "Bharat ka national animal kaunsa hai?", "opts": ["Lion", "Tiger", "Elephant", "Leopard"], "ans": "Tiger"},
    {"q": "Kaun sa janwar aaine me apna hi chehra dekh kar heran hota hai?", "opts": ["Kutta", "Billi", "Bandar", "Sher"], "ans": "Bandar"},
    {"q": "Duniya ka sabse uncha pahaad kaunsa hai?", "opts": ["K2", "Kanchenjunga", "Mount Everest", "Nanda Devi"], "ans": "Mount Everest"},
    {"q": "Sabse zyada kis gas se plants khana banate hain?", "opts": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], "ans": "Carbon Dioxide"},
    {"q": "Insaan ke shareer me sabse zyada kya hai?", "opts": ["Water (Pani)", "Blood (Khoon)", "Bones (Haddi)", "Fat (Charbi)"], "ans": "Water (Pani)"},
    {"q": "Kaun sa planet 'Red Planet' kehlata hai?", "opts": ["Mars", "Venus", "Jupiter", "Saturn"], "ans": "Mars"},
    {"q": "Duniya ka sabse bada ocean kaunsa hai?", "opts": ["Pacific", "Atlantic", "Indian", "Arctic"], "ans": "Pacific"},
    {"q": "Kaun si cheez heart (dil) ko pump karti hai?", "opts": ["Blood", "Oxygen", "Brain", "Muscles"], "ans": "Blood"},

    # History & General Knowledge
    {"q": "Mahatma Gandhi ko sabse zyada kise pyar tha?", "opts": ["Truth", "Money", "Power", "Fame"], "ans": "Truth"},
    {"q": "Sabse zyada kis desh ki cricket team ko world cup mila hai?", "opts": ["India", "West Indies", "Australia", "England"], "ans": "Australia"},
    {"q": "Bharat ki rajdhani kya hai?", "opts": ["Mumbai", "Kolkata", "New Delhi", "Chennai"], "ans": "New Delhi"},
    {"q": "Taj Mahal kis shahar me hai?", "opts": ["Delhi", "Agra", "Jaipur", "Lucknow"], "ans": "Agra"},
    {"q": "Bharat ka pehle Prime Minister kaun the?", "opts": ["Sardar Patel", "Jawaharlal Nehru", "Rajendra Prasad", "Lal Bahadur Shastri"], "ans": "Jawaharlal Nehru"},
    {"q": "Bharat ka constitution kab bana tha?", "opts": ["1947", "1949", "1950", "1952"], "ans": "1950"},
    {"q": "National Bird of India kaunsa hai?", "opts": ["Kaawa", "Mor (Peacock)", "Tota", "Kabootar"], "ans": "Mor (Peacock)"},
    {"q": "Which is the smallest country in the world?", "opts": ["Maldives", "Vatican City", "Monaco", "Sri Lanka"], "ans": "Vatican City"},
    {"q": "Bharat me 1 rupee ki sikka (coin) kis dhaatu se banti hai?", "opts": ["Sona", "Chandi", "Copper", "Steel"], "ans": "Steel"},

    # Fun & Riddles
    {"q": "Kaun sa din week ka sabse acha hota hai?", "opts": ["Monday", "Sunday", "Friday", "Saturday"], "ans": "Sunday"},
    {"q": "Jo khud bhooka rehta hai par dusron ko khilata hai, wo kaun?", "opts": ["Cook", "Farmer", "Doctor", "Driver"], "ans": "Cook"},
    {"q": "Aisi kya cheez hai jo utna zyada chhilke (peel) utni chhoti hoti hai?", "opts": ["Seb", "Kela", "Pyaaz", "Anaar"], "ans": "Pyaaz"},
    {"q": "Aisi kya cheez hai jise agar tum doba do to wo sukh (dry) ho jati hai?", "opts": ["Kapda", "Sponge", "Tauliya", "Pani"], "ans": "Tauliya"},
    {"q": "Aisa kaun hai jo bol nahi sakta par sabki sunta hai?", "opts": ["Bhains", "Kaanha", "Andha", "Behra"], "ans": "Bhains"},
    {"q": "Main aisi hoon jitna tum mujhe pehchano, utni main door ho jaati hoon. Main kya hoon?", "opts": ["Puzzle", "Dream", "Secret (Raaz)", "Night"], "ans": "Secret (Raaz)"},
    {"q": "Aisi kya cheez hai joagar tumne usko naam lekar bulaya to wo tut jati hai?", "opts": ["Aaina", "Kanch", "Shaanti (Silence)", "Toota hua dil"], "ans": "Shaanti (Silence)"},
    {"q": "Ek thaili (bag) me kya hai jo isko halka banata hai?", "opts": ["Hawa", "Kapde", "Pustak", "Pani"], "ans": "Hawa"},
    {"q": "Kaun sa fal mitai me aata hai aur sabzi me bhi?", "opts": ["Seb", "Kela", "Gajar", "Tamatar"], "ans": "Gajar"},
    {"q": "Kaun sa kaam hai jo tum akela nahi kar sakte?", "opts": ["Shaadi", "Khana", "Sona", "Hasna"], "ans": "Shaadi"}
]

# ==========================================
# WORD GUESS (CROSSWORD STYLE)
# ==========================================
WORD_PUZZLES = [
    {"q": "Paheli: Ek ghar bana, do darwaze, ek se aaye, ek se jaaye. Main kaun?", "ans": "Naak", "opts": ["Naak", "Kaan", "Aankh", "Muh"]},
    {"q": "Paheli: Pahaad jitna bhaari, par ek panchhi se ud jata hai. Main kaun?", "ans": "Baadal", "opts": ["Baadal", "Pahaad", "Suraj", "Chand"]},
    {"q": "Paheli: Main hamesha peechhe rehta hu, kabhi aage nahi aata. Main kaun?", "ans": "Beeta hua kal", "opts": ["Beeta hua kal", "Aane wala kal", "Aaj", "Subah"]},
    {"q": "Paheli: Main aisi cheez hu jo hawa me zinda, paani me mar jati hu. Main kaun?", "ans": "Aag", "opts": ["Aag", "Paani", "Hawa", "Mitti"]},
    {"q": "Paheli: Na main suraj hu na main chand, par raat me sabko dikhta hu. Main kaun?", "ans": "Tara", "opts": ["Tara", "Suraj", "Chand", "Badal"]},
    {"q": "Paheli: Main aisi cheez hu jo sabke paas hai, par kisi ko nahi chahiye. Main kaun?", "ans": "Bimari", "opts": ["Bimari", "Khushi", "Daulat", "Santusti"]},
    {"q": "Paheli: Main aisi cheez hu jo aasman me chhoti hoti hu aur zameen par badi. Main kaun?", "ans": "Patang", "opts": ["Patang", "Ghodi", "Ball", "Panchhi"]},
    {"q": "Paheli: Ek aisi cheez hai jo tutne par awaaz karti hai, uthane par nahi. Main kaun?", "ans": "Sheesha", "opts": ["Sheesha", "Lakdi", "Pathar", "Plastic"]},
    {"q": "Paheli: Na main bolta hu, na main sunta hu, par sabki baat manta hu. Main kaun?", "ans": "Kalam", "opts": ["Kalam", "Kaainchi", "Chaku", "Dawai"]},
    {"q": "Paheli: Main aisi cheez hu jo ghar me nahi, par ghar ke bahar ghoomti hu. Main kaun?", "ans": "Sadak", "opts": ["Sadak", "Ghar", "Khalihan", "Kholi"]},
    {"q": "Paheli: Na main dekhta hu, na main sunta hu, par main sab kuch karwata hu. Main kaun?", "ans": "Dimaag", "opts": ["Dimaag", "Hath", "Pair", "Pet"]},
    {"q": "Paheli: Sar ke bina ghoomta hu, pair ke bina jata hu. Main kaun?", "ans": "Pahiya", "opts": ["Pahiya", "Panchhi", "Ghoda", "Bacha"]},
    {"q": "Paheli: Main aisi cheez hu jo aapke paas hai, par aap mujhe doosro ko nahi de sakte. Main kaun?", "ans": "Naam", "opts": ["Naam", "Jeevan", "Maut", "Pehchaan"]},
    {"q": "Paheli: Aisa kaunsa phal hai jiska beej andar aur giri bahar?", "ans": "Anar", "opts": ["Anar", "Seb", "Kela", "Aam"]},
    {"q": "Paheli: Ek aisi dori hai jo tut-tu ke ek hi ban jati hai. Main kaun?", "ans": "Paani", "opts": ["Paani", "Rassi", "Dhaaga", "Lakdi"]},
    {"q": "Paheli: Main aisi cheez hu jo andar se kitni bhi ghani ho, par bahar se sab dikhe. Main kaun?", "ans": "Khidki", "opts": ["Khidki", "Deewar", "Darwaza", "Chhat"]},
    {"q": "Paheli: Main aisi cheez hu jo kabhi nahi sooti, par kabhi jagti bhi nahi. Main kaun?", "ans": "Neend", "opts": ["Neend", "Jagaran", "Bhookh", "Pyas"]},
    {"q": "Paheli: Sabse pehle main aata hu, par sabke baad mera naam aata hai. Main kaun?", "ans": "Aaj", "opts": ["Aaj", "Kal", "Parson", "Monday"]},
    {"q": "Paheli: Main aisi cheez hu jo gir toh jati hu par tutti nahi. Main kaun?", "ans": "Raat", "opts": ["Raat", "Din", "Sandhya", "Savere"]},
    {"q": "Paheli: Main aisi cheez hu jo paani me doob ke bhi nahi bheegti. Main kaun?", "ans": "Chhatri", "opts": ["Chhatri", "Topi", "Kapda", "Juta"]},
    {"q": "Paheli: Main aisi cheez hu jo andar se khaali ho toh bhari dikhti hu. Main kaun?", "ans": "Botal", "opts": ["Botal", "Balti", "Glass", "Box"]},
    {"q": "Paheli: Ek aisi gaadi jiska pahiya nahi, par chalti hai. Main kaun?", "ans": "Naav", "opts": ["Naav", "Bus", "Train", "Plane"]},
    {"q": "Paheli: Main aisi cheez hu jo barish me bheegti nahi, par dhoop me sookh jati hu. Main kaun?", "ans": "Paani", "opts": ["Paani", "Aag", "Dhoop", "Hawa"]},
    {"q": "Paheli: Main aisi cheez hu jo ek baar nikal gayi, toh kabhi wapas nahi aati. Main kaun?", "ans": "Saans", "opts": ["Saans", "Dhoop", "Hawa", "Pighal"]},
    {"q": "Paheli: Na main zinda hu, na murda, par sabka kaam karta hu. Main kaun?", "ans": "Robot", "opts": ["Robot", "Murti", "Insaan", "Pankha"]},
    {"q": "Paheli: Main aisi cheez hu jo bina bol-e sab samajh jata hu. Main kaun?", "ans": "Dil", "opts": ["Dil", "Dimaag", "Kaan", "Aankh"]},
    {"q": "Paheli: Main aisi cheez hu jo sab chah-te hain, par milne par chhupate hain. Main kaun?", "ans": "Paisa", "opts": ["Paisa", "Dosti", "Pyaar", "Khushi"]},
    {"q": "Paheli: Main aisi cheez hu jo utni badi hoti hu jitni tum khilate ho. Main kaun?", "ans": "Baloon", "opts": ["Baloon", "Ball", "Pippal", "Foosball"]},
    {"q": "Paheli: Sabse uncha pahaad bhi main hu, sabse neeche khadd bhi main hu. Main kaun?", "ans": "Aasmaan", "opts": ["Aasmaan", "Zameen", "Samundar", "Pahaad"]},
    {"q": "Paheli: Main aisi cheez hu jo ghar pe le ke ghoomta hu, par kuch karta nahi. Main kaun?", "ans": "Kachhua", "opts": ["Kachhua", "Kutta", "Billi", "Ghoda"]},
    {"q": "Paheli: Main aisi cheez hu jo sab ko aata hai, par koi mujhe pehchan-ta nahi. Main kaun?", "ans": "Maut", "opts": ["Maut", "Zindagi", "Neend", "Bimari"]},
    {"q": "Paheli: Main aisi cheez hu jo utna lamba hota hu jitna tum bhagao. Main kaun?", "ans": "Dhaaga", "opts": ["Dhaaga", "Rassi", "Wire", "Cable"]},
    {"q": "Paheli: Main aisi cheez hu jo chahiye toh mitti, par kaam aaye toh sona. Main kaun?", "ans": "Ann", "opts": ["Ann", "Paani", "Hawa", "Dhoop"]},
    {"q": "Paheli: Main aisi cheez hu jo aasmaan se girti hu, par zameen par nahi rehti. Main kaun?", "ans": "Dhool", "opts": ["Dhool", "Mitti", "Kapda", "Loha"]},
    {"q": "Paheli: Main aisa phal hu jo utna meetha hota hu jitna zyada kala ho. Main kaun?", "ans": "Kela", "opts": ["Kela", "Seb", "Santra", "Angoor"]},
    {"q": "Paheli: Na main kapda hu, na main chadar, par main sabko dhaak leta hu. Main kaun?", "ans": "Andhera", "opts": ["Andhera", "Ujala", "Roshni", "Dhoop"]},
    {"q": "Paheli: Ek aisi cheez hai jo bina haath pair ke ghar banati hai. Main kaun?", "ans": "Makdi", "opts": ["Makdi", "Makkhi", "Chinti", "Bhramar"]},
    {"q": "Paheli: Main aisi cheez hu jo utni lambi hoti hu jitna zyada kheencho. Main kaun?", "ans": "Rassi", "opts": ["Rassi", "Dhaaga", "Wire", "Cable"]},
    {"q": "Paheli: Na main paani hu na aag, par dono me kaam aata hu. Main kaun?", "ans": "Bartan", "opts": ["Bartan", "Chulha", "Pankha", "TV"]},
    {"q": "Paheli: Main aisi cheez hu jo chalti nahi, par jagah badalti hu. Main kaun?", "ans": "Parchai", "opts": ["Parchai", "Andhera", "Roshni", "Pencil"]},
    {"q": "Paheli: Ek aisi cheez hai jo thokne se banti hai, aur use karne ke liye thokna padta hai. Main kaun?", "ans": "Taali", "opts": ["Taali", "Sikka", "Ball", "Danda"]},
    {"q": "Paheli: Main aisa dhatu hu jo hazar baar pighlaaya ja sakta hai. Main kaun?", "ans": "Loha", "opts": ["Loha", "Sona", "Chandi", "Peetal"]},
    {"q": "Paheli: Main aisi cheez hu jo sab ke paas hoti hai, par use dekhne ke liye aaine ki zarurat hoti hai. Main kaun?", "ans": "Chehra", "opts": ["Chehra", "Hath", "Pair", "Parchai"]},
    {"q": "Paheli: Main aisi cheez hu jo zyada der paani me rahunga toh ghul jata hu. Main kaun?", "ans": "Baraf", "opts": ["Baraf", "Aag", "Paani", "Dhoop"]},
    {"q": "Paheli: Main aisi cheez hu jo bina aaye ya bina jaaye, aata hua nahi chhodta. Main kaun?", "ans": "Darwaza", "opts": ["Darwaza", "Khidki", "Deewar", "Chhat"]},
    {"q": "Paheli: Main aisi cheez hu jo paani me daalne par phool jati hu. Main kaun?", "ans": "Suji", "opts": ["Suji", "Atta", "Chawal", "Besan"]},
    {"q": "Paheli: Main aisi cheez hu jo aapke paas hai, par aap mujhe chhu nahi sakte. Main kaun?", "ans": "Dhoop", "opts": ["Dhoop", "Saans", "Hawa", "Pighal"]},
    {"q": "Paheli: Main aisi cheez hu jo andhere me kaam nahi aati, par ujale me sab kuch karti hu. Main kaun?", "ans": "Aankh", "opts": ["Aankh", "Kaan", "Naak", "Muh"]},
    {"q": "Paheli: Main aisi cheez hu jo ek baar chal di, toh kabhi wapas nahi aati. Main kaun?", "ans": "Waqt", "opts": ["Waqt", "Paisa", "Daulat", "Zindagi"]},
    {"q": "Paheli: Main aisi cheez hu jo utna chhupo, utna bada dikhta hai. Main kaun?", "ans": "Sach", "opts": ["Sach", "Jhoot", "Raaz", "Dhokha"]},
    {"q": "Paheli: Lal chidi gaadi khadi, ek utre toh sab roye. Main kaun?", "ans": "Pyaaz", "opts": ["Pyaaz", "Lehsun", "Adrak", "Tamatar"]},
    {"q": "Paheli: Andar hari, bahar lal, kato toh paani paani. Main kaun?", "ans": "Tarbooz", "opts": ["Tarbooz", "Kharbuza", "Seb", "Angoor"]},
    {"q": "Paheli: Das mote, ek patla, sabka kaam sambhalta. Main kaun?", "ans": "Sui", "opts": ["Sui", "Dhaga", "Kaainchi", "Chaku"]},
    {"q": "Paheli: Kala hua toh paani paani, paani me daala toh gayab. Main kaun?", "ans": "Shakkar", "opts": ["Shakkar", "Namak", "Atta", "Haldi"]},
    {"q": "Paheli: Ek behen do bhai, ek chala toh doosra aaye. Main kaun?", "ans": "Pair", "opts": ["Pair", "Hath", "Aankh", "Kaan"]},
    {"q": "Paheli: Na dekho toh ghus jaye, dekho toh tham jaye. Main kaun?", "ans": "Suraj", "opts": ["Suraj", "Chand", "Tara", "Badal"]},
    {"q": "Paheli: Bina aag ke roshan karta hai, bina paani ke jagmagata hai. Main kaun?", "ans": "Chand", "opts": ["Chand", "Suraj", "Tara", "Diya"]},
    {"q": "Paheli: Tum haso toh main hasu, tum ronu toh main ronu. Main kaun?", "ans": "Aaina", "opts": ["Aaina", "Photo", "Sheesha", "TV"]},
    {"q": "Paheli: Suraj aaye toh saath chalu, raat ho toh gayab. Main kaun?", "ans": "Parchai", "opts": ["Parchai", "Andhera", "Raat", "Neend"]},
    {"q": "Paheli: Main hamesha bhookha rehta hu, aur jitna khata hu, utna bada hota jata hu. Main kaun?", "ans": "Aag", "opts": ["Aag", "Paani", "Hawa", "Zameen"]},
    {"q": "Paheli: Ek aisa ghara hai jiske andar ek aur ghara hota hai, par dono tut-te hain. Main kaun?", "ans": "Anda", "opts": ["Anda", "Botal", "Dabba", "Pet"]},
    {"q": "Paheli: Sabke paas hota hai, par kisi ko nahi chahiye, jab chahiye toh gayab ho jata hai. Main kaun?", "ans": "Waqt", "opts": ["Waqt", "Paisa", "Maut", "Dukh"]},
    {"q": "Paheli: Utna chota jitna zyada mehnga. Main kaun?", "ans": "Heera", "opts": ["Heera", "Sona", "Moti", "Sikka"]},
    {"q": "Paheli: Main sabke paas hota hu, par chahiye kisi ko nahi. Main kaun?", "ans": "Dukh", "opts": ["Dukh", "Paisa", "Naam", "Kaam"]},
    {"q": "Paheli: Ped pe latakta hai, beej pe chatakta hai. Main kaun?", "ans": "Phal", "opts": ["Phal", "Phool", "Patta", "Jad"]},
    {"q": "Paheli: Hathi chala bazaar, jaisa chala waisa saajar. Main kaun?", "ans": "Juta", "opts": ["Juta", "Topi", "Kapda", "Bori"]},
    {"q": "Paheli: Kamre me ek, chhat pe do, bahar dekho toh sabhi. Main kaun?", "ans": "Taare", "opts": ["Taare", "Suraj", "Badal", "Chand"]},
    {"q": "Paheli: Hamesha aage rehta hu, par peeche se aawaz aati hai. Main kaun?", "ans": "Bijli", "opts": ["Bijli", "Badal", "Barish", "Hawa"]},
    {"q": "Paheli: Jab chaho tab la sakte ho, par pakad nahi sakte. Main kaun?", "ans": "Hawa", "opts": ["Hawa", "Paani", "Aag", "Dhoop"]},
    {"q": "Paheli: Garmi me aag lagau toh roye, sardi me dhoop me rakh du toh bhi roye. Main kaun?", "ans": "Baraf", "opts": ["Baraf", "Aag", "Paani", "Batti"]},
    {"q": "Paheli: Chidiya ne ande diye, log khane ko khade hue. Main kaun?", "ans": "Matar", "opts": ["Matar", "Chawal", "Dal", "Bhutte"]},
    {"q": "Paheli: Sab milke mujhe banate hain, par main kachcha kaam nahi aata. Main kaun?", "ans": "Eent", "opts": ["Eent", "Lakdi", "Pathar", "Cement"]},
    {"q": "Paheli: Main aisi cheez hu jo bina khaye marr jata hu. Main kaun?", "ans": "Bhookh", "opts": ["Bhookh", "Pyas", "Neend", "Maut"]},
    {"q": "Paheli: Meri aadat hai ek hi, par main badalta hu roz. Main kaun?", "ans": "Kal", "opts": ["Kal", "Aaj", "Din", "Raat"]},
    {"q": "Paheli: Ek aisi cheez hai jo bina haath pair ke bhaag-ti hai. Main kaun?", "ans": "Waqt", "opts": ["Waqt", "Paani", "Hawa", "Aag"]},
    {"q": "Paheli: Gagan me chubhta hu, par khoon nahi nikalta. Main kaun?", "ans": "Tara", "opts": ["Tara", "Suraj", "Chand", "Badal"]}
]
